import fs from 'node:fs';import {createHash,randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
import {LearningRepository} from '../../src/lib/server/learning/repository.ts';
const root='output/learning-compact-generation-20260923',hash=b=>createHash('sha256').update(b).digest('hex'),save=(f,v)=>fs.writeFileSync(root+'/'+f,JSON.stringify(v,null,2),{flag:'wx'});
assert(!fs.existsSync(root+'/recheck-plan.json'));
const before=fs.readFileSync(root+'/normal-material.txt','utf8'),from='风铃组完成检查且有绿卡，当前八枚点数，已实际印完三张：它剩两枚，不能立即再印下一批。',to='风铃组完成检查且有绿卡，印制前有八枚点数，现已实际印完三张；当前剩两枚，不能立即再印下一批。';assert(before.includes(from));const text=before.replace(from,to);
const session=JSON.parse(fs.readFileSync(root+'/session.json')),pageId=randomUUID(),materialId=randomUUID(),repo=new LearningRepository(root+'/data/users/'+session.userId,session.userId);
try{repo.create({id:pageId,title:'合成对照 · 展签印制课 v2（时点澄清）'});repo.saveMaterials(pageId,[{id:materialId,title:'展签印制规则 v2',kind:'txt',filename:'展签印制-v2.txt',bytes:Buffer.from(text)}]);save('recheck-input-catalog.json',[{pageId,materialId,kind:'txt',paragraphs:repo.source(pageId,materialId).paragraphs}]);}finally{repo.close();}
fs.writeFileSync(root+'/normal-material-v2.txt',text,{flag:'wx'});
const base=JSON.parse(fs.readFileSync(root+'/plan.json')).runs.find(x=>x.task==='N');
save('recheck-plan.json',{reason:'M1 Q2 correctOptionId points at an option contradicted by its own reason. Both models have fidelity issues. A separate v2 fixes a discovered sample time ambiguity, not a model prompt or answer-standard change.',cannotAttribute:'v2 is a new material version, not strict old/new A/B; compare only V1 vs V2 with each other',change:{from,to,oldSha256:hash(before),newSha256:hash(text)},frozenChecks:['same N rubric, all prerequisites explicit','no contradiction between selected answer and its own reason','all case evidence sufficient','no invented order; six means exactly consumed; independent obstacles','do not attribute the v1 ambiguous before/current wording entirely to either model'],runs:['deepseek-v4-pro','gpt-5.5'].map((model,i)=>({...base,label:'V'+(i+1),task:'N2',pair:'models-N2',id:randomUUID(),pageId,settings:{...base.settings,materialIds:[materialId]},model,encoding:'compact'}))});
fs.writeFileSync(root+'/recheck-plan.sha256',hash(fs.readFileSync(root+'/recheck-plan.json')));console.log(JSON.stringify({pageId,materialId,oldMaterialUnchanged:true,newVersion:true,calls:0}));
