// Final-answer-only evidence. This code never reads or exports model reasoning.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import Database from 'better-sqlite3';
const root=path.resolve('output/learning-compact-generation-20260923'),hash=b=>createHash('sha256').update(b).digest('hex'),save=(f,v)=>fs.writeFileSync(root+'/'+f,JSON.stringify(v,null,2));
const session=JSON.parse(fs.readFileSync(root+'/session.json')),plan=JSON.parse(fs.readFileSync(root+'/plan.json')),old=JSON.parse(fs.readFileSync(root+'/data-baseline.json'));
plan.runs.push(...JSON.parse(fs.readFileSync(root+'/recheck-plan.json')).runs);
const db=new Database(root+'/data/users/'+session.userId+'/learning-organizer.sqlite',{readonly:true});let oldCount=0;
try{assert.equal(db.pragma('integrity_check',{simple:true}),'ok');for(const[t,rows]of Object.entries(JSON.parse(fs.readFileSync(root+'/old-rows.json'))))for(const row of rows){const key=Object.keys(row).find(k=>k==='id')??null;if(!key){assert(db.prepare('SELECT * FROM '+t).all().some(r=>JSON.stringify(r)===JSON.stringify(row)));}else assert.equal(JSON.stringify(db.prepare('SELECT * FROM '+t+' WHERE id=?').get(row.id)),JSON.stringify(row),'Old row changed '+t);oldCount++;}}
finally{db.close();}assert.equal(hash(fs.readFileSync(old.source)),old.sha256,'Source course DB changed');save('data-audit.json',{originalDatabaseUnchanged:true,oldRowsUnchanged:oldCount,integrity:'ok'});
const rows=[];for(const f of fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]))){const n=f.match(/\d+/)[0],request=JSON.parse(fs.readFileSync(root+'/'+f)),response=JSON.parse(fs.readFileSync(root+'/ds-response-'+n+'.json')),step=plan.runs.find(r=>r.label===request.step),stored=fs.existsSync(root+'/'+request.step+'-stored.json')?JSON.parse(fs.readFileSync(root+'/'+request.step+'-stored.json')):null;
 let metadataOnly={};try{metadataOnly=JSON.parse(request.body.input.find(x=>x.role==='user').content??'{}');delete metadataOnly.materials;delete metadataOnly.extras;}catch{}
 const refs=request.body.input.map(x=>x.content).join('').match(/ref_[a-f0-9]{64}/g)??[];
 rows.push({n:Number(n),label:request.step,model:request.body.model,encoding:step?.encoding??'capability',requestedEffort:request.body.reasoning?.effort,returnedEffort:response.returnedReasoning?.effort??null,httpStatus:response.httpStatus,terminal:response.terminal,published:stored?.status??null,count:stored?.result_json?JSON.parse(stored.result_json).questions.length:0,failure:stored?.failure??response.failure??null,inputChars:request.inputChars,inputMetadataChars:JSON.stringify(metadataOnly).length,longReferenceChars:refs.length*68,finalChars:response.text?.length??0,finalLongReferenceChars:(response.text?.match(/ref_[a-f0-9]{64}/g)??[]).length*68,usage:response.usage,durationMs:response.durationMs,ttftMs:response.firstFinalTextMs});
 if(stored){const saved=stored.result_json?JSON.parse(stored.result_json):null;const catalog=new Map(saved?.questions.flatMap(q=>q.evidence?.map(e=>[e.referenceId,{text:e.quote,source:e.source}])??[])??[]);let parsed;try{parsed=JSON.parse(response.text);}catch{parsed={UNPARSED:response.text};}save('blind/'+request.step+'-readable.json',{label:request.step,published:stored.status,failure:stored.failure,raw:parsed,saved:saved?{title:saved.title,reason:saved.reason,questions:saved.questions.map(q=>({...q,evidence:q.evidence?.map(e=>({id:e.referenceId,text:e.quote,source:e.source}))}))}:null});}
}
save('ledger.json',{generatedRequests:rows.length,maxRequests:16,knownUsageResponses:rows.filter(r=>r.usage).length,unknownUsage:rows.filter(r=>!r.usage).map(r=>r.label),knownTotals:rows.filter(r=>r.usage).reduce((a,r)=>({input:a.input+r.usage.input_tokens,output:a.output+r.usage.output_tokens,total:a.total+r.usage.total_tokens}),{input:0,output:0,total:0}),rows});console.log(JSON.stringify({oldRows:oldCount,requests:rows.length,rows:rows.map(({label,model,encoding,published,count,durationMs,usage})=>({label,model,encoding,published,count,durationMs,usage}))}));
