import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium,expect as ex} from '@playwright/test';
import {root,base,save,vault} from './runtime.mjs';
const secure=vault('read'),s=JSON.parse(fs.readFileSync(root+'/session.json')),expect=ex.configure({timeout:90000}),count=()=>fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length,before=count();
const prefix=process.argv.includes('--production')?'production-':'',saveResult=(name,value)=>save(prefix+name,value);
const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1080},serviceWorkers:'block'}),tab=await ctx.newPage();ctx.setDefaultTimeout(90000);await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
const get=async(p,q)=>{const r=await tab.evaluate(async url=>{const r=await fetch(url,{credentials:'same-origin'});return{status:r.status,value:await r.json()};},'/api/learning/pages/'+p+q);assert.equal(r.status,200);return r.value;},snap=n=>tab.screenshot({path:root+'/screenshots/'+prefix+n+'.png',fullPage:true});
try{
 assert.equal((await ctx.request.post(base+'/api/auth/login',{data:{email:secure.email,password:secure.password}})).status(),200);
 await tab.goto(base+'/learning/'+s.pageId);await tab.getByRole('navigation',{name:'学习任务'}).getByRole('button',{name:'阅读框架',exact:true}).click();await tab.locator('summary').filter({hasText:'章节关系与总览'}).click();
 const overview=(await get(s.pageId,'/overview')).overview;assert(overview.published);saveResult('browser-overview.json',overview);await snap('overview-real-result');
 const sources=[];for(let i=0;i<overview.published.result.items.length;i++)for(let j=0;j<overview.published.result.items[i].sources.length;j++){const source=(await get(s.pageId,'/study-source?'+new URLSearchParams({kind:'overview',id:overview.published.id,item:String(i),index:String(j)}))).source;sources.push({kind:'overview',item:i,index:j,source});}
 await tab.getByRole('region',{name:'章节关系',exact:true}).getByRole('button',{name:/物理页/}).first().click();await expect(tab.locator('canvas[data-ready=true]')).toBeVisible();await snap('overview-pdf-region');await tab.getByRole('button',{name:'关闭原文',exact:true}).click();
 for(const [label,file]of [['A2','practice-open-A2-result.json'],['D3','test-complete-D3-result.json']]){const record=JSON.parse(fs.readFileSync(root+'/'+file)),a=record.attempt,pageId=new URL(record.url).pathname.split('/').at(-1);const reopened=(await get(pageId,'/quiz?attempt='+a.id)).attempt;assert.deepEqual(reopened,a);for(let i=0;i<reopened.questions.length;i++)for(let j=0;j<(reopened.questions[i].feedback?.sources.length??0);j++){const source=(await get(pageId,'/quiz?'+new URLSearchParams({attempt:a.id,question:String(i),source:String(j)}))).source;sources.push({kind:'quiz',label,question:i,index:j,source});}}
 assert.equal(count(),before);saveResult('browser-source-reads.json',sources);saveResult('inspect-result.json',{status:'PASS',sourceReads:sources.length,callsBefore:before,callsAfter:count(),oldPublishedPreservedAfterFailure:overview.latest.status==='failed'});console.log(JSON.stringify({status:'PASS',sourceReads:sources.length,calls:count()}));
}catch(e){saveResult('inspect-failure.json',{message:e.message});console.error(e.message);process.exitCode=1;}
finally{await browser.close();saveResult('inspect-exit.json',{exitCode:process.exitCode??0,browserClosed:true});}
