import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash,createHmac,randomUUID} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {chromium,expect as ex} from '@playwright/test';import Database from 'better-sqlite3';
import {root,save,vault} from './trial.mjs';
const phase=process.argv[2],secure=vault('read'),{base}=JSON.parse(fs.readFileSync(root+'/runtime.json','utf8')),expect=ex.configure({timeout:90000});
const safeError=e=>String(e?.message??e).split('Call log:')[0].replace(/daily_brief_session=[^\s"\\]+/g,'daily_brief_session=[REDACTED]');
const count=()=>({ds:fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length,ocr:fs.readdirSync(root).filter(f=>/^ocr-claim-/.test(f)).length,asr:fs.readdirSync(root).filter(f=>/^asr-submit-learning_/.test(f)).length});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1080},serviceWorkers:'block'});context.setDefaultTimeout(90000);
await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());const tab=await context.newPage(),errors=[],checks=[];
tab.on('pageerror',e=>errors.push(e.message));tab.on('dialog',d=>d.accept());let session=fs.existsSync(root+'/session.json')?JSON.parse(fs.readFileSync(root+'/session.json','utf8')):null,stage='login';
if(session?.pageId?.includes('?')){session.pageId=session.pageId.split('?')[0];save('session.json',session);}
const pass=message=>{checks.push(message);save('browser-'+phase+'-checks.json',checks);console.log(`[${phase} ${checks.length}] ${message}; calls ${JSON.stringify(count())}`);};
const snap=async name=>tab.screenshot({path:root+'/screenshots/'+name+'.png',fullPage:true});
// Chromium accepts Secure cookies on trustworthy loopback; APIRequestContext does not.
// Read the product API from the actual logged-in browser instead of weakening auth.
const api=async(route='',method='GET',data)=>tab.evaluate(async({url,method,data})=>{const r=await fetch(url,{method,credentials:'same-origin',...(data?{headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});return {status:r.status,value:await r.json()};},{url:base+'/api/learning/pages/'+session.pageId+route,method,data});
const area=async name=>tab.getByRole('navigation',{name:'学习任务'}).getByRole('button',{name,exact:true}).click();
const dbRead=fn=>{const db=new Database(root+'/data/users/'+session.userId+'/learning-organizer.sqlite',{readonly:true});try{return fn(db);}finally{db.close();}};
const audioSnapshot=()=>dbRead(db=>({runs:db.prepare('SELECT * FROM learning_audio_runs').all(),chunks:db.prepare('SELECT material_id,chunk_index,original_sha256,start_seconds,end_seconds,request_id,state,length(bytes) chunk_bytes,transcript_json FROM learning_audio_chunks').all(),transcripts:db.prepare('SELECT material_id,original_sha256,text,paragraphs_json FROM learning_audio_transcripts').all()}));
try{
 if(!session){const r=await context.request.post(base+'/api/auth/register',{data:{email:secure.email,password:secure.password,inviteCode:secure.invite},timeout:180000});assert.equal(r.status(),201);session={userId:(await r.json()).user.id};save('session.json',session);}else assert.equal((await context.request.post(base+'/api/auth/login',{data:{email:secure.email,password:secure.password},timeout:180000})).status(),200);
 if(!session.pageId){await tab.goto(base+'/learning');await tab.getByLabel('学习页名称').fill('合成课程 · 纸上展览工坊');await tab.getByRole('button',{name:'创建学习页',exact:true}).click();await expect(tab.getByRole('heading',{name:'合成课程 · 纸上展览工坊',exact:true})).toBeVisible();session.pageId=new URL(tab.url()).pathname.split('/').at(-1);save('session.json',session);}else await tab.goto(base+'/learning/'+session.pageId);
 if(phase==='prepare'){
  stage='mixed-upload';await area('材料');assert.equal((await api()).value.page.materials.length,0,'Do not reupload an existing course');
  await tab.getByLabel('添加 PDF',{exact:true}).setInputFiles(root+'/inputs/课程课件.pdf');await tab.getByLabel('添加已有录音',{exact:true}).setInputFiles(root+'/inputs/课程讲解.wav');await tab.getByLabel('导入 UTF-8 TXT',{exact:true}).setInputFiles(root+'/inputs/课堂笔记.txt');
  await tab.getByRole('button',{name:'保存材料 · 3 份',exact:true}).click();await expect(tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox')).toHaveCount(3);
  const saved=(await api()).value.page,frozen=JSON.parse(fs.readFileSync(root+'/frozen.json','utf8'));
  for(const m of saved.materials){const f=frozen.inputFiles.find(f=>f.name===m.filename);assert(f);if(m.kind!=='txt')assert.equal((m.pdf??m.audio).sha256,f.sha256);}
  save('materials-first.json',saved);const a=saved.materials.find(m=>m.kind==='audio');save('authorized-materials.json',[{userId:session.userId,pageId:session.pageId,materialId:a.id,sha256:a.audio.sha256}]);
  assert.deepEqual(count(),{ds:0,ocr:0,asr:0});await snap('01-three-inputs-save-only');pass('real mixed upload and persistent originals; zero AI requests');
  for(const c of await tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox').all())await c.check();await tab.getByRole('button',{name:'保存本次范围',exact:true}).click();await expect(tab.getByText('本次材料范围已保存。',{exact:true})).toBeVisible();
  const p=saved.materials.find(m=>m.kind==='pdf');await tab.getByRole('button',{name:'查看原页 '+p.title,exact:true}).click();await expect(tab.locator('canvas[data-ready=true]')).toBeVisible();await snap('02-original-before-ocr');await tab.getByRole('button',{name:'关闭原文',exact:true}).click();
  const tests=JSON.parse(fs.readFileSync(root+'/preflight-tests.json','utf8'));assert(tests.success&&tests.numPassedTests>0);
  const ssh=spawnSync('ssh',['-G','ubuntu-dev-lyc'],{encoding:'utf8',windowsHide:true});assert.equal(ssh.status,0);assert(ssh.stdout.split(/\r?\n/).some(s=>s.startsWith('identityfile ')&&fs.existsSync(s.slice(13).replace(/^~/,process.env.USERPROFILE))));
  save('local-preflight.json',{ready:true,at:new Date().toISOString(),originalsVerified:true,accountAndDatabasePrepared:true,uploadUI:true,adapterTests:tests.numPassedTests,sshConfigPresent:true,secureConfigPresent:true,providerCalls:count()});pass('local prerequisites ready before OCR service start');
 }else if(phase==='parse-first'||phase==='parse-second'){
  await area('材料');const saved=(await api()).value.page,p=saved.materials.find(m=>m.kind==='pdf'&&m.title===(phase==='parse-first'?'课程课件':'追加课件'));assert(p);const prior=await api('/materials/'+p.id+'/parsed');assert(!prior.value.documents?.some(d=>d.status==='completed'),'Already parsed: do not consume another request');
  const section=tab.locator('details').filter({has:tab.locator('summary').filter({hasText:'PDF 解析与学习范围 · '+p.title})}).first();await section.locator(':scope > summary').click();await section.getByLabel('结束物理页',{exact:true}).fill(String(p.pdf.pageCount));
  const response=tab.waitForResponse(r=>r.url().includes('/materials/'+p.id+'/parsed')&&r.request().method()==='POST',{timeout:1800000});await section.getByRole('button',{name:'解析选定 PDF 页',exact:true}).click();await expect(section.getByRole('status').filter({hasText:'正在解析'})).toBeVisible();await snap('03-'+phase+'-processing');
  const timer=setInterval(async()=>{try{const r=await api('/materials/'+p.id+'/parsed');save('progress-'+phase+'.json',r.value);console.log('['+phase+'] OCR requests '+count().ocr+'/30');}catch{}},15000);
  let r;try{r=await response;}finally{clearInterval(timer);}const result={status:r.status(),value:await r.json()};save(phase+'.json',result);assert.equal(r.status(),200);assert.equal(result.value.document.status,'completed');
  const reread=await api('/materials/'+p.id+'/parsed?document='+result.value.document.id);assert.deepEqual(reread.value.document,result.value.document);await snap('04-'+phase+'-completed-unverified');pass('real OCR response saved and reread, unverified retained');
 }else if(phase==='asr'){
  stage='asr';await area('材料');const a=(await api()).value.page.materials.find(m=>m.kind==='audio');assert.equal(a.audio.transcription,'not_transcribed','Already submitted: use explicit recovery, do not resubmit');
  const timer=setInterval(()=>{try{fs.appendFileSync(root+'/audio-checkpoints.jsonl',JSON.stringify({at:new Date().toISOString(),...audioSnapshot()})+'\n');}catch{}},1000);
  const response=tab.waitForResponse(r=>r.url().endsWith('/transcriptions')&&r.request().method()==='POST',{timeout:1500000});await tab.getByRole('button',{name:'转写所选录音',exact:true}).click();await expect(tab.getByRole('region',{name:'录音转写',exact:true})).toContainText(/正在转写|处理中/);await snap('05-asr-processing');
  let r;try{r=await response;}finally{clearInterval(timer);}save('asr-api.json',{status:r.status(),value:await r.json()});save('asr-stored.json',audioSnapshot());
  const source=await api('/materials/'+a.id);save('asr-source.json',source);assert.equal((await api()).value.page.materials.find(m=>m.id===a.id).audio.transcription,'completed');
  await tab.getByRole('button',{name:'查看原文 '+a.title,exact:true}).click();await expect(tab.getByRole('region',{name:'材料原文'})).toContainText('ASR 转写');assert.equal(await tab.locator('audio').count(),0);await snap('06-audio-time-source');pass('company ASR real segmented result saved with timed source; original retained');
 }else if(phase==='admit-first'||phase==='admit-second'){
  await area('材料');const p=(await api()).value.page.materials.find(m=>m.kind==='pdf'&&m.title===(phase==='admit-first'?'课程课件':'追加课件'));assert(p);
  const parsed=JSON.parse(fs.readFileSync(root+'/'+(phase==='admit-first'?'parse-first':'parse-second')+'.json','utf8')).value.document;
  const selection=JSON.parse(fs.readFileSync(root+'/review-only/'+phase+'.json','utf8'));assert.equal(selection.documentId,parsed.id);assert.equal(selection.originalSha256,parsed.originalSha256);
  const section=tab.locator('details').filter({has:tab.locator('summary').filter({hasText:'PDF 解析与学习范围 · '+p.title})}).first();await section.locator(':scope > summary').click();
  await expect(section.getByText(/内容未核实/).first()).toBeVisible();
  for(const page of parsed.pages){if(selection.physicalPages.includes(page.physical_page))await section.getByRole('checkbox',{name:new RegExp('^第 '+page.physical_page+' 物理页')}).check();
   const details=section.locator('details').filter({has:tab.locator('summary').filter({hasText:'查看解析文字与来源区域'})}).nth(page.physical_page-1);
   const ids=page.blocks.filter(b=>selection.excludedBlockIds.includes(b.id));if(ids.length){await details.locator(':scope > summary').click();for(const b of ids)await details.getByLabel('排除区域 '+b.id,{exact:true}).check();await details.locator(':scope > summary').click();}
  }
  await section.getByRole('checkbox',{name:/我已对照选定范围/}).check();if(selection.acknowledgeWarnings)await section.getByRole('checkbox',{name:/允许使用上述告警范围/}).check();
  await section.getByRole('button',{name:'保存 PDF 学习范围',exact:true}).click();await expect(section.getByText(/PDF 学习范围已保存/)).toBeVisible();await snap('07-'+phase+'-risks-and-exclusions');pass('reviewed scope explicitly admitted in UI; no verified upgrade, excluded blocks retained');
 }else if(phase==='direct-quiz'||phase==='joint-quiz'||phase==='cross-batch-quiz'){
  stage='quiz-generation';if(phase==='direct-quiz')assert.equal((await api('/framework')).value.framework.chapters.length,0);
  await area('材料');const quizMaterials=(await api()).value.page.materials;for(const [i,c] of (await tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox').all()).entries())await c.setChecked(phase==='cross-batch-quiz'||!['追加课件','追加记录'].includes(quizMaterials[i].title));const saveScope=tab.getByRole('button',{name:'保存本次范围',exact:true});if(await saveScope.isEnabled())await saveScope.click();
  await area('Quiz 练习');const q=tab.getByRole('region',{name:'单选 Quiz',exact:true});
  if(await q.getByRole('button',{name:'生成另一组',exact:true}).isVisible())await q.getByRole('button',{name:'生成另一组',exact:true}).click();
  if(!await q.getByLabel('题量',{exact:true}).isVisible()){await q.getByRole('button',{name:'题组与历史',exact:true}).click();await q.getByRole('button',{name:'生成另一组',exact:true}).click();}
  await q.getByLabel('题量',{exact:true}).fill('4');await q.getByLabel('难度').selectOption(phase==='direct-quiz'?'standard':'challenging');
  await q.getByRole('checkbox',{name:'纳入所选范围的个人笔记',exact:true}).setChecked(phase==='joint-quiz');await q.getByRole('checkbox',{name:'纳入所选知识点已保存的补充解释',exact:true}).setChecked(phase==='joint-quiz');
  save('ds-permits.json',[{name:phase,promptMarker:'你是学习单选题编写助手'}]);
  const response=tab.waitForResponse(r=>r.url().endsWith('/quiz')&&r.request().method()==='POST',{timeout:180000});await q.getByRole('button',{name:'生成 Quiz',exact:true}).click();await snap('08-'+phase+'-generating');const r=await response,v=await r.json();save(phase+'-api.json',{status:r.status(),value:v});assert.equal(r.status(),200);const quiz=v.quizzes[0];assert.equal(quiz.status,'completed',quiz.failure??quiz.reason??'Quiz not published');assert(quiz.count>=2,'Multi-question acceptance requires at least two');
  save('quiz-'+phase+'.json',dbRead(db=>db.prepare('SELECT * FROM learning_quiz_runs WHERE id=?').get(quiz.id)));await snap('09-'+phase+'-ready');pass('real '+phase+' published '+quiz.count+' questions with original source scope');
 }else if(phase==='framework-first'||phase==='framework-second'){
  const protectedBefore=phase==='framework-second'?{framework:(await api('/framework')).value.framework,quizzes:dbRead(db=>db.prepare('SELECT * FROM learning_quiz_runs ORDER BY id').all()),attempts:dbRead(db=>db.prepare('SELECT * FROM learning_quiz_attempts ORDER BY id').all())}:null;if(protectedBefore)save('before-second-generation.json',protectedBefore);
  stage='framework-generation';await area('材料');const materials=(await api()).value.page.materials;
  for(const m of materials){const second=['追加课件','追加记录'].includes(m.title);await tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox').filter({visible:true}).nth(materials.indexOf(m)).setChecked(phase==='framework-second'?second:!second);}
  const b=tab.getByRole('button',{name:'保存本次范围',exact:true});if(await b.isEnabled())await b.click();await area('阅读框架');const f=tab.getByRole('region',{name:'知识框架',exact:true});
  if(await f.getByRole('button',{name:'整理新材料',exact:true}).isVisible())await f.getByRole('button',{name:'整理新材料',exact:true}).click();
  save('ds-permits.json',[{name:phase,promptMarker:'你是学习整理助手'},...(phase==='framework-second'?[{name:'overview-second',promptMarker:'任务：在不同 runId'}]:[])]);
  const response=tab.waitForResponse(r=>r.url().endsWith('/framework')&&r.request().method()==='POST',{timeout:350000});await f.getByRole('button',{name:'整理所选材料',exact:true}).click();await snap('10-'+phase+'-generating');const r=await response,v=await r.json();save(phase+'-api.json',{status:r.status(),value:v});assert.equal(r.status(),200);assert(v.framework.chapters.length>0);assert(v.framework.runs.some(r=>r.status==='completed'));
  const after=(await api('/framework')).value.framework;save(phase+'-saved.json',after);save(phase+'-overview.json',(await api('/overview')).value);if(protectedBefore){for(const c of protectedBefore.framework.chapters)assert.deepEqual(after.chapters.find(n=>n.id===c.id),c);assert.deepEqual(dbRead(db=>db.prepare('SELECT * FROM learning_quiz_runs ORDER BY id').all()),protectedBefore.quizzes);assert.deepEqual(dbRead(db=>db.prepare('SELECT * FROM learning_quiz_attempts ORDER BY id').all()),protectedBefore.attempts);pass('append generation preserved every old chapter, edit, note, quiz and attempt');}await snap('11-'+phase+'-reading');pass('real framework saved and reopened; '+after.chapters.length+' chapters');
 }else if(phase==='qa'||phase==='edit'){
  const framework=(await api('/framework')).value.framework;
  let chosen=fs.existsSync(root+'/chosen-node.json')?JSON.parse(fs.readFileSync(root+'/chosen-node.json','utf8')):null;
  if(!chosen){const pairs=framework.chapters.flatMap(c=>c.nodes.map(n=>({c,n})));const pick=pairs.filter(p=>/前提|时间检查|团体/.test(p.n.title)).sort((a,b)=>b.n.sources.length-a.n.sources.length)[0]??pairs[0];chosen={chapterId:pick.c.id,nodeId:pick.n.id};save('chosen-node.json',chosen);}
  const chapter=framework.chapters.find(c=>c.id===chosen.chapterId),node=chapter.nodes.find(n=>n.id===chosen.nodeId);await area('阅读框架');await tab.getByRole('navigation',{name:'章节目录'}).getByRole('button').nth(framework.chapters.indexOf(chapter)).click();
  const article=tab.getByRole('article',{name:node.title,exact:true});
  if(phase==='qa'){
   const query='?'+new URLSearchParams({chapter:chapter.id,node:node.id});const old=(await api('/node-qa'+query)).value.conversations;assert(old.length<=1&&old.every(c=>c.turns.every(t=>t.status==='completed')),'Do not retry failed or pending turns');const completedTurns=old[0]?.turns.length??0;assert(completedTurns<=2);
   await article.getByRole('button',{name:'没看懂 / 继续追问',exact:true}).click();const dialog=tab.getByRole('dialog',{name:'没看懂 / 继续追问',exact:true});
   const questions=['请结合这个知识点解释：不满足适用前提，和满足前提后检查没有通过，有什么区别？保留材料中的条件和待确认事项。','请接着用一个明确标为假设的日常教学例子解释刚才的区别，不要把例子当作本课事实。'];
   for(let i=completedTurns;i<questions.length;i++){save('ds-permits.json',[{name:'node-question-'+(i+1),promptMarker:'任务：围绕当前node'}]);await dialog.getByLabel('继续追问',{exact:true}).fill(questions[i]);const r=tab.waitForResponse(r=>r.url().endsWith('/node-qa')&&r.request().method()==='POST',{timeout:180000});await dialog.getByRole('button',{name:'发送问题',exact:true}).click();const result=await r;save('qa-'+(i+1)+'-api.json',{status:result.status(),value:await result.json()});assert.equal(result.status(),200);await expect(dialog.getByLabel('继续追问',{exact:true})).toBeEnabled();await snap('12-qa-turn-'+(i+1));}
   const conversations=(await api('/node-qa'+query)).value.conversations;assert.equal(conversations.length,1);assert.equal(conversations[0].turns.length,2);assert(conversations[0].turns.every(t=>t.status==='completed'));assert.equal(conversations[0].turns[1].contextTurnIds.length,1);
   const note=dialog.getByRole('button',{name:'将这条补充存为笔记',exact:true});if(await note.count())await note.last().click();else await dialog.getByRole('button',{name:'将材料解释存为笔记',exact:true}).last().click();await expect(dialog.getByRole('button',{name:'已存为笔记',exact:true}).first()).toBeVisible();save('qa-saved.json',(await api('/node-qa'+query)).value);await snap('13-qa-saved-note');pass('two real turns share saved context; explicit explanation-to-note action');
  }else{
   await article.locator('summary').filter({hasText:'更多'}).click();await article.getByRole('button',{name:'编辑知识点 / 笔记',exact:true}).click();const form=tab.getByRole('form',{name:'编辑框架',exact:true});
   await form.getByLabel('标题',{exact:true}).fill(node.title+'（我的整理）');await form.getByLabel('解释',{exact:true}).fill(node.explanation+'\n\n【用户编辑】我先区分适用前提与执行后的结果，再判断。');await form.getByLabel('个人笔记',{exact:true}).fill(node.note+'\n\n【个人笔记】我想用两栏列出“能否使用规则”和“使用后的结果”，这是我的学习方法，不是新增课程规则。');await form.getByRole('button',{name:'保存修改',exact:true}).click();await expect(form).not.toBeVisible();save('before-append-framework.json',(await api('/framework')).value.framework);save('before-append-quizzes.json',dbRead(db=>db.prepare('SELECT * FROM learning_quiz_runs').all()));save('before-append-attempts.json',dbRead(db=>db.prepare('SELECT * FROM learning_quiz_attempts').all()));await snap('14-user-edit-note');pass('user edit and personal note saved; immutable pre-append snapshots');
  }
 }else if(['practice','test','resume-test','cross-start','restart-check'].includes(phase)){
  const initial=count();await area('Quiz 练习');const q=tab.getByRole('region',{name:'单选 Quiz',exact:true});
  const target=phase==='practice'?'direct-quiz':phase==='cross-start'||phase==='restart-check'?'cross-batch-quiz':'joint-quiz';
  const saved=JSON.parse(fs.readFileSync(root+'/quiz-'+target+'.json','utf8')),quiz=JSON.parse(saved.result_json);await q.getByRole('button',{name:'题组与历史',exact:true}).click();
  const item=q.getByRole('listitem').filter({hasText:quiz.title});await item.getByRole('button',{name:/使用这组题|续做/}).click();
  const mode=phase==='practice'?'practice':'test';if(await q.getByRole('button',{name:'开始作答',exact:true}).isVisible()){await q.getByRole('radio',{name:mode==='practice'?/^练习/:/^测验/}).check();await q.getByRole('button',{name:'开始作答',exact:true}).click();}
  await expect(tab).toHaveURL(/attempt=/);await expect(q.getByRole('article',{name:'当前作答'})).toBeVisible();const attemptId=new URL(tab.url()).searchParams.get('attempt');assert(attemptId);save('attempt-'+target+'.json',{id:attemptId,quizId:saved.id,mode});
  const initialAttempt=await api('/quiz?attempt='+attemptId);if(initialAttempt.status!==200)save('browser-'+phase+'-attempt-read-failure-'+Date.now()+'.json',initialAttempt);assert.equal(initialAttempt.status,200,'Read stored attempt');let a=initialAttempt.value.attempt;assert.equal(a.mode,mode);if(!a.completed&&mode==='test')assert(a.questions.every(x=>x.feedback===undefined));
  const actUI=async(label)=>{console.log('['+phase+'] '+label);const response=tab.waitForResponse(r=>r.url().endsWith('/quiz')&&r.request().method()==='PATCH');await q.getByRole('button',{name:label,exact:true}).click();const r=await response;assert.equal(r.status(),200);await expect(q.getByRole('status').filter({hasText:/正在保存/})).toHaveCount(0);};
  if(phase==='restart-check'){
   const prior=JSON.parse(fs.readFileSync(root+'/restart-before.json','utf8'));assert.deepEqual(a,prior.attempt);assert.deepEqual((await api()).value.page,prior.page);assert.deepEqual((await api('/framework')).value.framework,prior.framework);await snap('24-restart-restored');pass('same persistent course, framework, notes and unfinished test restored after full stop/restart');
  }
  console.log('['+phase+'] attempt opened '+attemptId);const startIndex=Number(new URL(tab.url()).searchParams.get('question')??0);
  const end=phase==='restart-check'?Math.min(startIndex+1,a.questions.length):(phase==='test'||phase==='cross-start')?Math.min(2,a.questions.length):a.questions.length;
  for(let i=startIndex;i<end;i++){
   a=(await api('/quiz?attempt='+attemptId)).value.attempt;const current=a.questions[i],article=q.getByRole('article',{name:'当前作答'});
   console.log('['+phase+'] question '+i+' '+JSON.stringify(current.progress));if(!current.progress.submitted&&!current.progress.skipped&&!current.progress.revealed){
    if(i===0&&!current.progress.hinted)await actUI('提示');
    const known=fs.existsSync(root+'/review-only/skip-known-questions.json')?JSON.parse(fs.readFileSync(root+'/review-only/skip-known-questions.json','utf8')):{};if((i===1&&phase==='practice')||known[saved.id]?.includes(i))await actUI('跳过本题');else{
     if(current.progress.optionId!==current.options[0].id){const response=tab.waitForResponse(r=>r.url().endsWith('/quiz')&&r.request().method()==='PATCH');await article.locator('input[type=radio]').first().click();assert.equal((await response).status(),200);}await expect(article.getByRole('status')).toContainText('选择已保存');
     if(mode==='practice')await actUI('确认答案');
    }
   }
   await snap((mode==='practice'?'16-practice':'17-test')+'-'+i);a=(await api('/quiz?attempt='+attemptId)).value.attempt;
   if(mode==='test'&&!a.completed)assert(a.questions.every(x=>x.feedback===undefined),'No answer leakage');
   if(i<quiz.questions.length-1){await q.getByRole('button',{name:'下一题',exact:true}).click();}
  }
  if(phase==='test'||phase==='cross-start'||phase==='restart-check'){
   a=(await api('/quiz?attempt='+attemptId)).value.attempt;assert(!a.completed);save('unfinished-'+target+'.json',a);const url=tab.url();save('resume-url-'+target+'.json',{url});await tab.reload();await expect(q.getByRole('article',{name:'当前作答'})).toBeVisible();assert.deepEqual((await api('/quiz?attempt='+attemptId)).value.attempt,a);
   assert.equal(await tab.evaluate(async()=> (await fetch('/api/auth/logout',{method:'POST'})).status),200);await context.clearCookies();assert.equal((await context.request.post(base+'/api/auth/login',{data:{email:secure.email,password:secure.password}})).status(),200);await tab.goto(url);await expect(q.getByRole('article',{name:'当前作答'})).toBeVisible();assert.deepEqual((await api('/quiz?attempt='+attemptId)).value.attempt,a);await snap('18-resume-'+target);
   if(phase==='cross-start')save('restart-before.json',{attempt:a,page:(await api()).value.page,framework:(await api('/framework')).value.framework,counts:count()});pass('multi-question test autosaved; refresh and re-login restore choice, hint and order');
  }else{
   if(await q.getByRole('button',{name:'查看本次结果',exact:true}).isVisible())await q.getByRole('button',{name:'查看本次结果',exact:true}).click();else await actUI('交卷并查看结果');
   await expect(q.getByLabel('本次结果',{exact:true})).toBeVisible();a=(await api('/quiz?attempt='+attemptId)).value.attempt;assert(a.completed);assert(a.score);save('completed-'+target+'.json',a);await snap('19-result-'+target);pass('real '+mode+' completed, all stored option IDs/order preserved with feedback');
  }
  assert.deepEqual(count(),initial,'Answering/reopening cannot call models');
 }else if(phase==='overview-recheck'){
  const before=(await api('/overview')).value.overview;assert.equal(before.latest.failure,'overview_invalid_relation');save('overview-recheck-before.json',before);await area('阅读框架');await tab.locator('summary').filter({hasText:'章节关系与总览'}).click();save('ds-permits.json',[{name:phase,promptMarker:'任务：在不同 runId'}]);const response=tab.waitForResponse(r=>r.url().endsWith('/overview')&&r.request().method()==='POST',{timeout:180000});await tab.getByRole('button',{name:'更新关系总览',exact:true}).click();const r=await response;save('overview-recheck-api.json',{status:r.status(),value:await r.json()});const after=(await api('/overview')).value.overview;save('overview-recheck-saved.json',after);assert.equal(after.latest.status,'completed');await expect(tab.getByRole('region',{name:'章节关系',exact:true})).toContainText(after.published.result.summary);await snap('15-cross-batch-relations');pass('manual bounded overview recheck published; prior invalid-ID response preserved');
 }else if(phase==='restored-evidence'){
  const initial=count(),f=(await api('/framework')).value.framework,chosen=JSON.parse(fs.readFileSync(root+'/chosen-node.json','utf8'));
  const conversations=(await api('/node-qa?'+new URLSearchParams({chapter:chosen.chapterId,node:chosen.nodeId}))).value.conversations;
  const expected=JSON.parse(fs.readFileSync(root+'/qa-saved.json','utf8')).conversations;
  assert.equal(conversations.length,1);assert.deepEqual(conversations[0].turns,expected[0].turns);assert.deepEqual(audioSnapshot(),JSON.parse(fs.readFileSync(root+'/asr-stored.json','utf8')));
  const frozen=JSON.parse(fs.readFileSync(root+'/frozen.json','utf8')),originals=dbRead(db=>db.prepare('SELECT id,filename,original FROM learning_materials WHERE page_id=? AND deleted_at IS NULL').all(session.pageId));
  for(const m of originals)assert.equal(createHash('sha256').update(m.original).digest('hex'),frozen.inputFiles.find(x=>x.name===m.filename).sha256);
  await area('阅读框架');await tab.locator('summary').filter({hasText:'章节关系与总览'}).click();const overview=(await api('/overview')).value.overview;assert.equal(overview.latest.status,'failed');assert.equal(overview.published,null);await expect(tab.getByText('尚无关系总览，章节与来源仍可阅读。',{exact:true})).toBeVisible();await snap('15-cross-batch-overview-not-published');
  const chapter=f.chapters.find(c=>c.id===chosen.chapterId),node=chapter.nodes.find(n=>n.id===chosen.nodeId);await tab.getByRole('navigation',{name:'章节目录'}).getByRole('button').nth(f.chapters.indexOf(chapter)).click();await tab.getByRole('article',{name:node.title,exact:true}).getByRole('button',{name:'没看懂 / 继续追问',exact:true}).click();await expect(tab.getByRole('dialog',{name:'没看懂 / 继续追问',exact:true})).toContainText('请接着用一个');await snap('30-restarted-conversation');
  save('restored-evidence.json',{status:'PASS',originalHashes:originals.length,asrCheckpointUnchanged:true,turns:conversations[0].turns.length,overviewStatus:overview.latest.status,overviewPublished:false});assert.deepEqual(count(),initial);pass('restarted originals, ASR checkpoints and both QA turns are unchanged; failed overview remains honestly unpublished');
 }else if(phase==='security-delete'){
  const initial=count(),mainId=session.pageId,page=(await api()).value.page,pdf=page.materials.find(m=>m.kind==='pdf'),audio=page.materials.find(m=>m.kind==='audio'),run=JSON.parse(fs.readFileSync(root+'/asr-stored.json','utf8')).runs[0];const security=[];
  const route='/api/learning/asr-audio/'+[session.userId,mainId,run.id,audio.id,0].join('/');
  const signed=(expires)=>{const capability=createHmac('sha256',secure.secret).update(['v1','transcription',session.userId,`learning:${mainId}:${run.id}:${audio.id}`,0,String(expires)].join('\0')).digest('base64url');return new URLSearchParams({expires:String(expires),purpose:'transcription',capability});};
  for(const [name,query,wanted] of [['expired',signed(Math.floor(Date.now()/1000)-1),401],['wrong-signature',new URLSearchParams({expires:String(Math.floor(Date.now()/1000)+299),purpose:'transcription',capability:'invalid'}),401],['completed-task',signed(Math.floor(Date.now()/1000)+299),404]]){const r=await context.request.get(base+route+'?'+query);assert.equal(r.status(),wanted);security.push({check:name,status:r.status()});}
  const anonymous=await browser.newContext();try{for(const suffix of ['/materials/'+pdf.id+'/pdf','/materials/'+audio.id]){const r=await anonymous.request.get(base+'/api/learning/pages/'+mainId+suffix);assert([401,403].includes(r.status()));security.push({check:'unauthenticated-'+suffix.split('/').at(-1),status:r.status()});}
   const r=await anonymous.request.post(base+'/api/auth/register',{data:{email:'other-'+randomUUID()+'@synthetic.invalid',password:randomUUID()+randomUUID(),inviteCode:secure.invite}});assert.equal(r.status(),201);const foreign=await anonymous.newPage();await foreign.goto(base+'/learning');for(const method of ['GET','HEAD']){const status=await foreign.evaluate(async({path,method})=>(await fetch(path,{method,headers:{Range:'bytes=0-99'}})).status,{path:'/api/learning/pages/'+mainId+'/materials/'+pdf.id+'/pdf',method});assert([403,404].includes(status));security.push({check:'cross-account-pdf-'+method,status});}}
  finally{await anonymous.close();}
  save('security-route-checks.json',security);stage='delete-copy-create';await tab.goto(base+'/learning');await tab.getByRole('button',{name:'新建学习页',exact:true}).click();await tab.getByLabel('学习页名称').fill('[删除验收副本] 不保留课程');await tab.getByRole('button',{name:'创建学习页',exact:true}).click();await expect(tab.getByRole('heading',{name:'[删除验收副本] 不保留课程'})).toBeVisible();session={...session,pageId:new URL(tab.url()).pathname.split('/').at(-1)};await area('材料');stage='delete-copy-materials';
  await tab.getByLabel('添加 PDF',{exact:true}).setInputFiles(root+'/inputs/追加课件.pdf');await tab.getByLabel('导入 UTF-8 TXT',{exact:true}).setInputFiles(root+'/inputs/追加记录.txt');await tab.getByRole('button',{name:'保存材料 · 2 份',exact:true}).click();await expect(tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox')).toHaveCount(2);const copy=(await api()).value.page,copyPdf=copy.materials.find(m=>m.kind==='pdf');
  await tab.getByRole('button',{name:'查看原页 '+copyPdf.title,exact:true}).click();await expect(tab.locator('canvas[data-ready=true]')).toBeVisible();await tab.getByRole('button',{name:'关闭原文',exact:true}).click();await tab.getByRole('button',{name:'删除材料 '+copyPdf.title,exact:true}).click();const dialog=tab.getByRole('dialog');await expect(dialog).toContainText('保留已有学习成果和作答记录');await snap('28-material-delete-confirmation');await dialog.getByRole('button',{name:'删除这份材料',exact:true}).click();await expect(tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox')).toHaveCount(1);const missing=await api('/materials/'+copyPdf.id+'/pdf');assert([404,410].includes(missing.status));await tab.reload();await expect(tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox')).toHaveCount(1);
  await tab.locator('summary').filter({hasText:'学习页管理'}).click();await tab.getByRole('button',{name:'删除学习页',exact:true}).click();await expect(tab.getByRole('dialog')).toContainText('全部材料、框架、笔记、对话和练习记录');await snap('29-page-delete-confirmation');await tab.getByRole('dialog').getByRole('button',{name:'删除学习页',exact:true}).click();await expect(tab).toHaveURL(base+'/learning');assert([404,410].includes((await api()).status));session={...session,pageId:mainId};assert.equal((await api()).value.page.materials.length,5);save('security-delete-result.json',{security,copyPage:copy.id,deletedPdfStatus:missing.status,originalCoursePreserved:true});assert.deepEqual(count(),initial);pass('real local route denial and separate-page browser deletion; no generation or course data loss');
 }else if(phase==='sources'){
  const initial=count(),f=(await api('/framework')).value.framework,materials=(await api()).value.page.materials,checks=[];await area('阅读框架');
  for(const kind of ['pdf','audio','txt']){
   let pick;for(const c of f.chapters){for(const n of c.nodes){const i=n.sources.findIndex(s=>materials.find(m=>m.id===s.materialId)?.kind===kind);if(i>=0&&(!pick||n.sources.length>pick.n.sources.length))pick={c,n,i};}}
   assert(pick);await tab.getByRole('navigation',{name:'章节目录'}).getByRole('button').nth(f.chapters.indexOf(pick.c)).click();const article=tab.getByRole('article',{name:pick.n.title,exact:true}),ref=pick.n.sources[pick.i];await article.scrollIntoViewIfNeeded();await snap('20-multisource-node-'+kind);const y=await tab.evaluate(()=>window.scrollY);
   const res=await api('/framework/source?'+new URLSearchParams({chapter:pick.c.id,node:pick.n.id,index:String(pick.i)}));assert.equal(res.status,200);assert.equal(res.value.source.paragraph.number,ref.paragraph);
   await article.getByLabel('知识点来源',{exact:true}).getByRole('button').nth(pick.i).click();const drawer=tab.getByRole('region',{name:'材料原文',exact:true});await expect(drawer).toBeVisible();
   if(kind==='pdf'){await expect(drawer.locator('canvas[data-ready=true]')).toHaveAttribute('data-physical-page',String(ref.parsed.physicalPage));await drawer.getByLabel('缩放',{exact:true}).selectOption('1.5');await expect(drawer.locator('canvas[data-ready=true]')).toBeVisible();await drawer.getByRole('button',{name:'展开阅读',exact:true}).click();await snap('21-pdf-region-expanded');await drawer.getByRole('button',{name:'恢复侧栏宽度',exact:true}).click();}
   else{await expect(drawer.locator('#learning-paragraph-'+ref.paragraph)).toHaveAttribute('data-current','true');if(kind==='audio'){assert(Number.isFinite(res.value.source.paragraph.startSeconds));await expect(drawer).toContainText('ASR 转写');assert.equal(await tab.locator('audio').count(),0);}}
   await snap('22-source-'+kind);await drawer.getByRole('button',{name:'关闭原文',exact:true}).click();await expect(drawer).not.toBeVisible();assert(Math.abs((await tab.evaluate(()=>window.scrollY))-y)<120);checks.push({kind,chapter:pick.c.id,node:pick.n.id,ref,source:res.value.source});
  }
  save('real-source-ui-checks.json',checks);await tab.setViewportSize({width:390,height:844});await area('材料');await snap('25-mobile-materials');assert(await tab.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await area('阅读框架');await tab.getByLabel('当前章节').selectOption(f.chapters.at(-1).id);await snap('26-mobile-framework');assert(await tab.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await area('Quiz 练习');await snap('27-mobile-quiz');assert(await tab.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));assert.deepEqual(count(),initial);pass('actual PDF region, ASR time and TXT paragraph sources; zoom/back and mobile layout');
 }else if(phase==='append'){
  await area('材料');const saved=(await api()).value.page;assert.equal(saved.materials.length,3,'Append only once');
  await tab.getByLabel('添加 PDF',{exact:true}).setInputFiles(root+'/inputs/追加课件.pdf');await tab.getByLabel('导入 UTF-8 TXT',{exact:true}).setInputFiles(root+'/inputs/追加记录.txt');await tab.getByRole('button',{name:'保存材料 · 2 份',exact:true}).click();await expect(tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox')).toHaveCount(5);save('materials-second.json',(await api()).value.page);pass('second batch appended without automatic processing');
 }
 save('browser-'+phase+'-result.json',{status:'PASS',checks,errors,counts:count()});assert.deepEqual(errors,[]);
}catch(e){save('browser-'+phase+'-failure-'+Date.now()+'.json',{stage,error:safeError(e),counts:count()});console.error('Browser '+phase+' failed at '+stage+': '+safeError(e));await snap('failure-'+phase).catch(()=>{});process.exitCode=1;}
finally{await browser.close();save('browser-'+phase+'-exit-'+Date.now()+'.json',{exitCode:process.exitCode??0,stage,browserClosed:true});}
