// Real saved course copied only for destructive local consistency checks; no service replay/call.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import Database from 'better-sqlite3';
import {LearningRepository} from '../../src/lib/server/learning/repository.ts';
import {LearningFrameworkRepository} from '../../src/lib/server/learning/framework-repository.ts';
const root=path.resolve('output/learning-synthetic-course-20260923'),session=JSON.parse(fs.readFileSync(root+'/session.json','utf8')),dir=root+'/deletion-copy-'+Date.now();fs.mkdirSync(dir);
const originalFile=root+'/data/users/'+session.userId+'/learning-organizer.sqlite',original=new Database(originalFile,{readonly:true});
const originals=()=>original.prepare('SELECT id,original FROM learning_materials WHERE page_id=? AND deleted_at IS NULL').all(session.pageId).map(r=>({id:r.id,hash:createHash('sha256').update(r.original).digest('hex')}));
const beforeOriginal=originals();await original.backup(dir+'/learning-organizer.sqlite');const repo=new LearningRepository(dir,session.userId),framework=new LearningFrameworkRepository(repo),page=session.pageId,materials=repo.get(page).materials;
const results=()=>({chapters:repo.database.prepare('SELECT * FROM learning_framework_chapters WHERE page_id=? ORDER BY id').all(page),quizzes:repo.database.prepare("SELECT * FROM learning_quiz_runs WHERE page_id=? AND status='completed' ORDER BY id").all(page),attempts:repo.database.prepare('SELECT * FROM learning_quiz_attempts WHERE page_id=? ORDER BY id').all(page),turns:repo.database.prepare("SELECT * FROM learning_node_turns WHERE page_id=? AND status='completed' ORDER BY id").all(page)});
const before=results(),pending=randomUUID();let stage='begin';
try{framework.begin(page,{id:pending,materialIds:materials.map(m=>m.id)},48000);stage='material deletion';const ids=materials.filter(m=>m.kind==='pdf'||m.kind==='audio').map(m=>m.id);
 for(const id of ids){repo.deleteMaterial(page,id);assert.throws(()=>repo.source(page,id),/material_deleted/);const m=repo.database.prepare('SELECT original FROM learning_materials WHERE id=?').get(id);assert.equal(m.original,null);assert.equal(repo.database.prepare('SELECT count(*) n FROM learning_audio_chunks WHERE material_id=?').get(id).n,0);assert.equal(repo.database.prepare('SELECT count(*) n FROM learning_audio_transcripts WHERE material_id=?').get(id).n,0);assert.equal(repo.database.prepare('SELECT count(*) n FROM learning_parsed_documents WHERE material_id=? AND result_json IS NOT NULL').get(id).n,0);}
 assert.deepEqual(results(),before);const actual=JSON.parse(JSON.parse(fs.readFileSync(root+'/ds-response-3.json','utf8')).text);assert.throws(()=>framework.complete(page,pending,actual),/framework_terminal|material_deleted/);assert.throws(()=>framework.begin(page,{id:randomUUID(),materialIds:[ids[0]]},48000),/material_deleted/);
 const otherDir=dir+'/other-account';const other=new LearningRepository(otherDir,'different-isolated-account');try{assert.throws(()=>other.get(page),/page_not_found/);}finally{other.close();}
 stage='page deletion';repo.deletePage(page);for(const table of ['learning_materials','learning_parsed_documents','learning_framework_chapters','learning_quiz_runs','learning_quiz_attempts','learning_node_turns','learning_node_conversations','learning_overview_runs'])assert.equal(repo.database.prepare('SELECT count(*) n FROM '+table+' WHERE page_id=?').get(page).n,0);
 assert.throws(()=>framework.complete(page,pending,actual),/page_deleted|page_not_found/);assert.deepEqual(originals(),beforeOriginal);
 fs.writeFileSync(root+'/deletion-copy-result.json',JSON.stringify({status:'PASS',copy:dir,source:'SQLite online backup of actual saved trial results; not Provider rerun',originalCourseUnchanged:true,materialsDeleted:ids.length,preservedBeforePageDelete:{chapters:before.chapters.length,quizzes:before.quizzes.length,attempts:before.attempts.length,turns:before.turns.length},latePublishBlocked:true,crossAccountRejected:true},null,2));console.log('Deletion copy PASS; original course preserved');
}catch(e){fs.writeFileSync(root+'/deletion-copy-failure-'+Date.now()+'.json',JSON.stringify({stage,error:e.message,copy:dir}));process.exitCode=1;console.error('Deletion copy failed: '+e.message);}finally{repo.close();original.close();fs.writeFileSync(root+'/deletion-copy-exit.json',JSON.stringify({exitCode:process.exitCode??0}));}
