// Bounded evidence closeout; does not call Providers or modify preserved course data.
import fs from 'node:fs';import path from 'node:path';import net from 'node:net';
import {createHash} from 'node:crypto';import {parseEnv} from 'node:util';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
import {root,save,vault} from './trial.mjs';
const runtime=JSON.parse(fs.readFileSync(root+'/runtime.json','utf8'));
const ports=[];for(const port of[37910,37911,37912,37913]){const open=await new Promise(resolve=>{const s=net.connect({host:'127.0.0.1',port});let done=false;const finish=value=>{if(done)return;done=true;s.destroy();resolve(value);};s.once('connect',()=>finish(true));s.once('error',()=>finish(false));s.setTimeout(1000,()=>finish(false));});ports.push({port,listening:open});}
assert(ports.every(p=>!p.listening),'Owned local listener remains');
const remote=JSON.parse(fs.readFileSync(root+'/ocr-cleanup-final.json','utf8'));assert(remote.cleanup_verified&&remote.remaining_pids.length===0&&remote.remaining_gpu.length===0&&remote.remaining_listeners.length===0);
const secure=vault('read');assert(!secure.ocrToken,'Transient OCR capability remains');
const cfg=parseEnv(fs.readFileSync('.env.local','utf8'));const secrets=[secure.secret,secure.password,secure.invite,cfg.OPENAI_API_KEY].filter(Boolean),findings=[];
for(const f of fs.readdirSync(root)){if(!/\.(jsonl?|log)$/.test(f)||!fs.statSync(root+'/'+f).isFile())continue;const text=fs.readFileSync(root+'/'+f,'utf8');if(secrets.some(s=>text.includes(s))||/capability=[A-Za-z0-9_-]{35,}/.test(text))findings.push(f);}
save('secret-scan.json',{filesWithSecrets:findings});assert.equal(findings.length,0,'Evidence needs credential redaction');
const sourceFiles=['src/lib/server/learning/quiz-service.ts','src/lib/server/learning/framework-generator.ts','src/lib/server/learning/study-service.ts','src/lib/server/learning/study-repository.ts','src/lib/server/learning/quiz-grounding.ts','src/components/learning/learning-study.tsx','src/components/learning/learning-quiz.tsx','src/lib/server/learning/quiz-reference.test.ts','src/lib/server/learning/study.test.ts','src/components/learning/learning-study.test.tsx','src/components/learning/learning-quiz.test.tsx','docs/learning-synthetic-course-trial.md',...fs.readdirSync('scripts/learning-synthetic-course').map(f=>'scripts/learning-synthetic-course/'+f)];
const hashes=sourceFiles.map(file=>({file,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')}));save('final-code.json',{at:new Date().toISOString(),files:hashes});
for(const[name,args]of[['head',['rev-parse','HEAD']],['branch',['branch','--show-current']],['status',['status','--short']],['staged',['diff','--cached','--name-only']],['diff-check',['-c','core.safecrlf=false','diff','--check']]]){const r=spawnSync('git',args,{encoding:'utf8',windowsHide:true});fs.writeFileSync(root+'/final-'+name+'.txt',r.stdout??'');save('final-'+name+'-exit.json',{exitCode:r.status});assert.equal(r.status,0,'git '+name);}
const calls={ds:fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length,ocrPages:fs.readdirSync(root).filter(f=>/^ocr-claim-/.test(f)).length,asrSubmits:fs.readdirSync(root).filter(f=>/^asr-submit-learning_/.test(f)).length};assert.deepEqual(calls,{ds:11,ocrPages:12,asrSubmits:2});
const exits=fs.readdirSync(root).filter(f=>/^runtime-exit-\d+\.json$/.test(f)).sort(),last=JSON.parse(fs.readFileSync(root+'/'+exits.at(-1),'utf8'));assert.equal(last.code,0);assert(last.cleanup.every(p=>p.exitCode===0));
save('final-cleanup.json',{status:'PASS',at:new Date().toISOString(),ports,localRuntime:last,remoteCleanupVerified:true,remoteRemainingOwnedProcesses:0,remoteRemainingOwnedGpuProcesses:0,remoteRemainingOwnedListeners:0,secureConfigRetained:true,transientOcrTokenRemoved:true,courseDataRetained:true,calls});
console.log(JSON.stringify({status:'PASS',calls,localPortsClosed:ports.length,remoteCleanupVerified:true,courseDataRetained:true,secretsFound:findings.length}));
