// Reuse unmodified delivered lifecycle scripts in a separate authorized batch.
import fs from 'node:fs';import assert from 'node:assert/strict';import net from 'node:net';import {spawn,spawnSync} from 'node:child_process';
import {root,save,vault} from './trial.mjs';
const hand=JSON.parse(fs.readFileSync('C:/Codex/learning-ocr-handoff/20260921-171314/service-handoff.json','utf8'));
const old=hand.server_runtime_directory,remote=old.replace(/\/[^/]+$/,'/core-synthetic-course-20260923'),py=hand.lifecycle.python;
const ssh=(command,input)=>{const r=spawnSync('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=12','ubuntu-dev-lyc',command],{input,encoding:'utf8',windowsHide:true,timeout:60000,maxBuffer:2*1024*1024});if(r.error)throw Error('SSH_'+r.error.code);return r;};
const json=relative=>{const r=ssh(`cat '${remote}/${relative}'`);assert.equal(r.status,0,'Remote receipt unavailable');return JSON.parse(r.stdout);};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const action=process.argv[2];
if(action==='prepare'){
 assert(JSON.parse(fs.readFileSync(root+'/local-preflight.json','utf8')).ready);
 const code=`import pathlib,json,hashlib,shutil,sys,os\nold=pathlib.Path('${old}');new=pathlib.Path('${remote}')\nsys.path.insert(0,str(old/'scripts'))\nimport common\nrevision=common.verify()\nassert not new.exists(),'Independent batch already exists; do not reset it'\nold_budget=json.loads((old/'evidence/budget.json').read_text())\nold_attempts=len((old/'evidence/start-attempts.jsonl').read_text().splitlines())\nnew.mkdir(mode=0o700)\nfor d in ['evidence','private','outputs','logs','configs','scripts','adapter']: (new/d).mkdir(mode=0o700)\nfor folder in ['scripts','configs','adapter']:\n for p in (old/folder).iterdir():\n  if p.is_file(): shutil.copyfile(p,new/folder/p.name)\n(new/'cache').symlink_to(old/'cache',target_is_directory=True)\nplan=json.loads((old/'evidence/frozen-plan.json').read_text());plan['budgets']={'starts':4,'pages':30,'http':500}\n(new/'evidence/frozen-plan.json').write_text(json.dumps(plan,indent=2))\nfor f in ['adapter-source.json']: shutil.copyfile(old/'evidence'/f,new/'evidence'/f)\n(new/'evidence/budget.json').write_text(json.dumps({'starts':0,'pages':0,'http':0}))\nmanifest=json.loads((old/'evidence/launch-integrity.json').read_text())\nfor folder in ['scripts','configs','adapter','evidence']:\n for p in (new/folder).iterdir():\n  if p.is_file() and p.name!='budget.json': manifest['files'].append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})\nmanifest['revision']=revision+'-independent-course-budget'\n(new/'evidence/launch-integrity.json').write_text(json.dumps(manifest,indent=2))\nreceipt={'new_batch':str(new),'parent_revision':revision,'old_budget_preserved':old_budget,'old_starts_preserved':old_attempts,'new_caps':plan['budgets'],'script_code_changed':False,'global_lock_unchanged':True,'model_config_unchanged':True}\n(new/'evidence/batch-authorization.json').write_text(json.dumps(receipt,indent=2));print(json.dumps(receipt))`;
 const r=ssh(`${py} -`,code);save('ocr-prepare.json',{exitCode:r.status,stdout:r.stdout,stderr:r.stderr});assert.equal(r.status,0,'Remote batch preparation failed');console.log('Independent OCR batch prepared; zero starts');
}else if(action==='start'){
 assert(JSON.parse(fs.readFileSync(root+'/local-preflight.json','utf8')).ready);
 const attempts=fs.readdirSync(root).filter(f=>/^ocr-start-\d+\.json$/.test(f));assert(attempts.length<4);
 await new Promise((r,j)=>{const s=net.createServer();s.once('error',j);s.listen(37913,'127.0.0.1',()=>s.close(r));});
 const pre=ssh(`${py} -`, `import sys,pathlib,json\nsys.path.insert(0,'${remote}/scripts');import common;common.verify()\np=pathlib.Path('${remote}/evidence/start-attempts.jsonl');assert (len(p.read_text().splitlines()) if p.exists() else 0)<4\nprint(json.dumps({'integrity':True,'budget':json.loads(pathlib.Path('${remote}/evidence/budget.json').read_text())}))`);save('ocr-prestart.json',{exitCode:pre.status,stdout:pre.stdout,stderr:pre.stderr});assert.equal(pre.status,0);
 save('ocr-start-'+(attempts.length+1)+'.json',{at:new Date().toISOString(),status:'claimed_before_start'});
 const r=ssh(`${py} '${remote}/scripts/start.py' pdf`);save('ocr-start-result-'+(attempts.length+1)+'.json',{exitCode:r.status,stdout:r.stdout,stderr:r.stderr});assert.equal(r.status,0);const owned=JSON.parse(r.stdout);save('ocr-owned.json',{...owned,remote});
 const deadline=Date.now()+730000;let ready=false;
 while(Date.now()<deadline){const h=ssh(`${py} '${remote}/scripts/health.py'`);save('ocr-health.json',{exitCode:h.status,stdout:h.stdout,stderr:h.stderr});try{if(JSON.parse(h.stdout).ready){ready=true;break;}}catch{}const active=json('evidence/active-instance.json');assert.equal(active.pid,owned.supervisor_pid);const summary=ssh(`test ! -f '${remote}/outputs/${active.instance}/summary.json'`);if(summary.status!==0)throw Error('OCR supervisor stopped; inspect owned summary');await wait(4000);}
 assert(ready,'OCR readiness timeout');const token=ssh(`cat '${remote}/private/api-key'`);assert.equal(token.status,0);assert(token.stdout.trim().length>=20);const secure=vault('read');secure.ocrToken=token.stdout.trim();vault('write',secure);
 console.log('OCR READY; secure token updated. Start tunnel separately, no parse requests made');
}else if(action==='tunnel'){
 const c=spawn('ssh',['-N','-o','BatchMode=yes','-o','ExitOnForwardFailure=yes','-o','ServerAliveInterval=30','-L','127.0.0.1:37913:127.0.0.1:46238','ubuntu-dev-lyc'],{windowsHide:true,stdio:'ignore'});
 const deadline=Date.now()+30000;let ready=false;while(Date.now()<deadline){assert(c.exitCode===null,'Tunnel exited');ready=await new Promise(r=>{const s=net.createConnection({host:'127.0.0.1',port:37913});s.setTimeout(750);s.once('connect',()=>{s.destroy();r(true)});s.once('error',()=>r(false));s.once('timeout',()=>{s.destroy();r(false)});});if(ready)break;await wait(300);}assert(ready);
 const sec=vault('read');const h=await fetch('http://127.0.0.1:37913/health',{headers:{Authorization:'Bearer '+sec.ocrToken},signal:AbortSignal.timeout(5000)});assert.equal(h.status,200);save('ocr-local-health.json',await h.json());save('tunnel.json',{pid:c.pid,ownerPid:process.pid,port:37913});console.log('SSH PDF-only forward READY');
 const stop=()=>{if(c.exitCode===null)spawnSync('taskkill',['/PID',String(c.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});};process.on('SIGINT',stop);process.on('SIGTERM',stop);
 while(!fs.existsSync(root+'/stop-tunnel')&&c.exitCode===null)await wait(500);stop();save('tunnel-exit.json',{exitCode:c.exitCode,stopped:true});
}else if(action==='stop'){
 const own=JSON.parse(fs.readFileSync(root+'/ocr-owned.json','utf8')),active=json('evidence/active-instance.json');assert.equal(active.pid,own.supervisor_pid,'Ownership changed: do not stop');
 const r=ssh(`${py} '${remote}/scripts/stop.py'`);save('ocr-stop-'+Date.now()+'.json',{exitCode:r.status,stdout:r.stdout,stderr:r.stderr});assert.equal(r.status,0);
 save('ocr-budget-final.json',json('evidence/budget.json'));save('ocr-cleanup-final.json',json('outputs/'+active.instance+'/summary.json'));
 const secure=vault('read');delete secure.ocrToken;vault('write',secure);fs.writeFileSync(root+'/stop-tunnel','stop');console.log('Owned OCR stopped and cleanup recorded');
}else if(action==='status')console.log(JSON.stringify({active:json('evidence/active-instance.json'),budget:json('evidence/budget.json')}));
