import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {root,save} from './trial.mjs';
const repo=process.cwd(),kind=process.argv[2],slash=p=>p.replaceAll('\\','/'),before=fs.readFileSync('next-env.d.ts'),env={};
for(const[k,v]of Object.entries(process.env))if(/^(path|pathext|systemroot|windir|comspec|temp|tmp|userprofile|localappdata|appdata|homedrive|homepath|processor_architecture|number_of_processors)$/i.test(k))env[k]=v;
const config=root+'/verify-tsconfig.json',dist=path.relative(repo,root+'/build');
save('verify-tsconfig.json',{extends:slash(repo+'/tsconfig.json'),compilerOptions:{incremental:false,baseUrl:slash(repo),paths:{'@/*':['./src/*']}},include:['src/**/*.ts','src/**/*.tsx','scripts/**/*.ts','scripts/**/*.tsx','tests/**/*.ts','tests/**/*.tsx','*.ts'].map(p=>slash(repo+'/'+p)).concat([slash(root+'/build/types/**/*.ts')]),exclude:[slash(repo+'/node_modules'),slash(repo+'/output'),slash(repo+'/.data'),slash(repo+'/test-data')]});
Object.assign(env,{APP_DATA_DIR:root+'/verification-data',DATA_DIR:root+'/verification-data',APP_STORAGE_MODE:'local',SPEAKER_ASR_BASE_URL:'https://asr.disabled.invalid',NEXT_TELEMETRY_DISABLED:'1',DAILY_BRIEF_E2E_DIST_DIR:slash(dist),DAILY_BRIEF_E2E_TSCONFIG:slash(path.relative(repo,config)),LEARNING_VALIDATION_REPO:repo,LEARNING_TRIAL_ROOT:root,LEARNING_TRIAL_LIVE:'0',NODE_OPTIONS:`--max-old-space-size=8192 --require="${slash(repo+'/scripts/learning-synthetic-course/guard.cjs')}"`});
const run=(name,args)=>{const start=Date.now(),r=spawnSync(process.execPath,args,{env,encoding:'utf8',windowsHide:true,maxBuffer:30*1024*1024});fs.writeFileSync(root+'/'+name+'.log',(r.stdout??'')+(r.stderr??''));const receipt={command:[process.execPath,...args],exitCode:r.status,error:r.error?.code,durationMs:Date.now()-start};save(name+'-exit.json',receipt);console.log(JSON.stringify(receipt));return r.status??1;};
try{if(kind==='typecheck'){process.exitCode=run('typegen',['node_modules/next/dist/bin/next','typegen']);if(!process.exitCode)process.exitCode=run('typecheck',['node_modules/typescript/bin/tsc','--noEmit','--incremental','false','-p',config]);}else if(kind==='build')process.exitCode=run('build',['node_modules/next/dist/bin/next','build']);else throw Error('Choose typecheck or build');}
finally{if(fs.readFileSync('next-env.d.ts','utf8').includes('learning-synthetic-course-20260923/build'))fs.writeFileSync('next-env.d.ts',before);}
