import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {LearningRepository} from '../../src/lib/server/learning/repository.ts';import {LearningQuizRepository} from '../../src/lib/server/learning/quiz-repository.ts';import {quizReferenceId} from '../../src/lib/server/learning/quiz-grounding.ts';
const root=path.resolve('output/learning-input-scope-20260924'),session=JSON.parse(fs.readFileSync(root+'/session.json')),plan=JSON.parse(fs.readFileSync(root+'/plan.json')),learning=new LearningRepository(root+'/data/users/'+session.userId,session.userId),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),save=(f,v)=>fs.writeFileSync(root+'/'+f,JSON.stringify(v,null,2));
try{const ledger=[],results=[];let sourceReads=0,pdfReads=0,audioReads=0,noteReads=0;for(const f of fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]))){const n=f.match(/\d+/)[0],req=JSON.parse(fs.readFileSync(root+'/'+f)),res=JSON.parse(fs.readFileSync(root+'/ds-response-'+n+'.json')),step=plan.runs.find(s=>s.label===req.step),stored=JSON.parse(fs.readFileSync(root+'/'+step.label+'-stored.json')),published=stored.result_json?JSON.parse(stored.result_json):null;ledger.push({n:Number(n),label:step.label,kind:step.kind,view:step.view,inputChars:req.inputChars,http:res.httpStatus,terminal:res.terminal,status:stored.status,count:published?.questions?.length??null,usage:res.usage,durationMs:res.durationMs,returnedModel:res.returnedModel,returnedReasoning:res.returnedReasoning,incomplete:res.incomplete});if(step.kind!=='quiz')continue;
 const wire=JSON.parse(req.body.input.find(m=>m.role==='user').content),binding=JSON.parse(stored.binding_json),raw=JSON.parse(res.text),mapping=new Map();let i=0;for(const m of binding.materials)for(const p of m.paragraphs)mapping.set('r'+(++i),quizReferenceId({materialId:m.materialId,originalSha256:m.originalSha256,paragraph:p}));for(const e of binding.extras)mapping.set('r'+(++i),quizReferenceId(e));
 const qrepo=new LearningQuizRepository(learning);for(const q of published?.questions??[]){const original=raw.items.find(x=>q.stem.endsWith(x.stem));assert(original);assert.equal(q.correctOptionId,original.correctOptionId);for(const o of q.options){const old=original.options.find(x=>x.id===o.id);assert(old);assert.deepEqual(o.evidenceIds,old.evidenceIds.map(id=>mapping.get(id)));assert.equal(o.reason,old.reason,'No silent rewriting of option reasons in these fixtures');}for(const s of q.sources){const actual=qrepo.source(step.pageId,s);sourceReads++;if(s.kind==='note'){noteReads++;assert.equal(actual.text,plan.personalNote);}if(s.parsed){pdfReads++;assert.deepEqual(actual.paragraph.parsed,s.parsed);const doc=learning.getParsedDocument(step.pageId,s.parsed.documentId),p=doc.pages.find(p=>p.physical_page===s.parsed.physicalPage),b=p.blocks.find(b=>b.id===s.parsed.blockId);assert(p.render&&b.source_regions.length);assert.equal(b.source_sha256,s.parsed.sourceHash);}if(s.startSeconds!==undefined){audioReads++;assert.equal(actual.paragraph.startSeconds,s.startSeconds);assert.equal(actual.paragraph.endSeconds,s.endSeconds);}}
 }
 const current=learning.database.prepare('SELECT result_json FROM learning_quiz_runs WHERE id=?').get(step.id);assert.equal(current.result_json,stored.result_json);results.push({label:step.label,status:stored.status,questions:published?.questions?.length??0,exactOptionMapping:true,savedResultUnchanged:true,sourceRisksPreserved:wire.taskContext.materialCatalog.filter(m=>m.scopeNotice).map(m=>m.scopeNotice)});}
 const old=JSON.parse(fs.readFileSync(root+'/old-rows.json')),changes=[];let unchanged=0;for(const [table,rows]of Object.entries(old)){const now=learning.database.prepare('SELECT * FROM '+table+' ORDER BY rowid').all();for(const [index,row]of rows.entries()){const current=JSON.parse(JSON.stringify(now[index]));assert(current,'Old row lost');const fields=Object.keys(row).filter(k=>JSON.stringify(row[k])!==JSON.stringify(current[k]));if(fields.length)changes.push({table,id:row.id,fields});else unchanged++;}}save('history-preservation.json',{unchangedOldRows:unchanged,changes,sourceDatabaseUnchanged:hash(fs.readFileSync(JSON.parse(fs.readFileSync(root+'/data-baseline.json')).source))===JSON.parse(fs.readFileSync(root+'/data-baseline.json')).sha256});
 save('source-roundtrip.json',{sourceReads,pdfReads,audioReads,noteReads,results});save('ledger.json',{maxRequests:12,used:ledger.length,ocr:0,asr:0,server:0,rows:ledger});console.log(JSON.stringify({requests:ledger.length,sourceReads,pdfReads,audioReads,noteReads,unchangedOldRows:unchanged,changes,ledger:ledger.map(r=>({label:r.label,status:r.status,count:r.count,input:r.usage?.input_tokens,output:r.usage?.output_tokens,ms:r.durationMs}))}));
}finally{learning.close();}
