// Browser-only use of already generated real groups. No generation permits.
import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium,expect as ex} from '@playwright/test';import {root,base,save,vault} from './runtime.mjs';
const phase=process.argv[2],target=process.argv[3],secure=vault('read'),session=JSON.parse(fs.readFileSync(root+'/session.json','utf8')),expect=ex.configure({timeout:90000});
session.pageId=JSON.parse(fs.readFileSync(root+'/plan.json')).runs.find(r=>r.label===target).pageId;
const count=()=>fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length,initial=count(),saved=JSON.parse(fs.readFileSync(root+'/'+target+'-stored.json','utf8')),quiz=JSON.parse(saved.result_json);
assert.equal(saved.status,'completed');const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1080},serviceWorkers:'block'}),tab=await ctx.newPage();ctx.setDefaultTimeout(90000);tab.on('dialog',d=>d.accept());const errors=[];tab.on('pageerror',e=>errors.push(e.message));
await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
const api=async suffix=>tab.evaluate(async url=>{const r=await fetch(url,{credentials:'same-origin'});return{status:r.status,value:await r.json()};},'/api/learning/pages/'+session.pageId+suffix),snap=n=>tab.screenshot({path:root+'/screenshots/'+n+'.png',fullPage:true});
const login=async()=>assert.equal((await ctx.request.post(base+'/api/auth/login',{data:{email:secure.email,password:secure.password}})).status(),200);
try{
 await login();const resume=['restart-resume','restart-one'].includes(phase)?JSON.parse(fs.readFileSync(root+'/resume-'+target+'.json','utf8')):null;
 await tab.goto(resume?.url??base+'/learning/'+session.pageId);await tab.getByRole('navigation',{name:'学习任务'}).getByRole('button',{name:'Quiz 练习',exact:true}).click();const q=tab.getByRole('region',{name:'单选 Quiz',exact:true});
 if(!resume){await q.getByRole('button',{name:'题组与历史',exact:true}).click();const item=q.getByRole('listitem').filter({hasText:quiz.title});await item.getByRole('button',{name:/使用这组题|续做/}).click();if(await q.getByRole('button',{name:'开始作答',exact:true}).isVisible()){await q.getByRole('radio',{name:phase==='practice-open'?/^练习/:/^测验/}).check();await q.getByRole('button',{name:'开始作答',exact:true}).click();}}
 await expect(q.getByRole('article',{name:'当前作答'})).toBeVisible();const id=new URL(tab.url()).searchParams.get('attempt');assert(id);const get=async()=>{const r=await api('/quiz?attempt='+id);assert.equal(r.status,200);return r.value.attempt;};let a=await get();if(resume)assert.deepEqual(a,resume.attempt,'Restart must restore exact progress and order');
 const act=async label=>{const [r]=await Promise.all([tab.waitForResponse(r=>r.url().endsWith('/quiz')&&r.request().method()==='PATCH'),q.getByRole('button',{name:label,exact:true}).click()]);assert.equal(r.status(),200);await expect(q.getByRole('status').filter({hasText:/正在保存/})).toHaveCount(0);};
 const start=Number(new URL(tab.url()).searchParams.get('question')??0),end=phase==='practice-open'?1:phase==='restart-one'?Math.min(start+1,a.questions.length):a.questions.length;
 for(let i=start;i<end;i++){
  a=await get();const cur=a.questions[i],article=q.getByRole('article',{name:'当前作答'});if(!cur.progress.submitted&&!cur.progress.skipped&&!cur.progress.revealed){
   if(i===0&&!cur.progress.hinted)await act('提示');
   if(i===1&&!resume)await act('跳过本题');else{const option=phase==='test-complete'&&i===2?quiz.questions[i].options.find(o=>o.id!==quiz.questions[i].correctOptionId).id:quiz.questions[i].correctOptionId;if(cur.progress.optionId!==option){const [r]=await Promise.all([tab.waitForResponse(r=>r.url().endsWith('/quiz')&&r.request().method()==='PATCH'),article.locator('input[type=radio][value="'+option+'"]').click()]);assert.equal(r.status(),200);}await expect(article.getByRole('status')).toContainText('选择已保存');if(a.mode==='practice')await act('确认答案');}
  }
  a=await get();if(a.mode==='test')assert(a.questions.every(x=>x.feedback===undefined),'No pre-submit answers');else if(i===0){assert(a.questions[0].feedback);const source=article.getByRole('button',{name:/PDF · 第/}).first();if(await source.isVisible()){await source.click();await expect(tab.getByRole('region',{name:'材料原文',exact:true})).toBeVisible();await expect(tab.locator('canvas[data-ready=true]')).toBeVisible();await snap(phase+'-pdf-source');await tab.getByRole('button',{name:'关闭原文',exact:true}).click();}}
  if(phase==='restart-one'){const audio=article.getByRole('button',{name:'原材料 · 第 16 段',exact:true});if(await audio.isVisible()){await audio.click();const source=tab.getByRole('region',{name:'材料原文',exact:true});await expect(source).toContainText('ASR 转写');await expect(source.locator('#learning-paragraph-16')).toContainText('秒');await snap('restart-audio-time-source');await tab.getByRole('button',{name:'关闭原文',exact:true}).click();}}
  await snap(phase+'-'+i);if(phase==='test-complete'&&i===0){const partial=await get();await tab.reload();await expect(q.getByRole('article',{name:'当前作答'})).toBeVisible();assert.deepEqual(await get(),partial,'Mid-test refresh must retain progress without revealing answers');await snap('test-middle-refresh');}if(i<a.questions.length-1)await q.getByRole('button',{name:'下一题',exact:true}).click();
 }
 a=await get();if(phase==='test-complete'){if(await q.getByRole('button',{name:'查看本次结果',exact:true}).isVisible())await q.getByRole('button',{name:'查看本次结果',exact:true}).click();else await act('交卷并查看结果');await expect(q.getByLabel('本次结果',{exact:true})).toBeVisible();a=await get();assert(a.completed);await snap('practice-result');}
 const url=tab.url();await tab.reload();await expect(q).toBeVisible();assert.deepEqual(await get(),a);assert.equal(await tab.evaluate(async()=> (await fetch('/api/auth/logout',{method:'POST'})).status),200);await ctx.clearCookies();await login();await tab.goto(url);await expect(q).toBeVisible();assert.deepEqual(await get(),a);await snap(phase+'-relogin');
 if(!a.completed)save('resume-'+target+'.json',{url,attempt:a});save(phase+'-'+target+'-result.json',{status:'PASS',attempt:a,url,dsBefore:initial,dsAfter:count(),pageErrors:errors});assert.equal(count(),initial);assert.deepEqual(errors,[]);console.log(JSON.stringify({phase,target,status:'PASS',progress:a.questions.map(q=>q.progress),calls:count()}));
}catch(e){console.error(String(e.message).split('Call log:')[0]);save('consume-'+phase+'-failure-'+Date.now()+'.json',{message:String(e.message).split('Call log:')[0]});await snap('consume-'+phase+'-failure').catch(()=>{});process.exitCode=1;}
finally{await browser.close();save('consume-'+phase+'-exit-'+Date.now()+'.json',{exitCode:process.exitCode??0,browserClosed:true});}
