import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {parseEnv} from 'node:util';import Database from 'better-sqlite3';
const old=path.resolve('output/learning-compact-generation-20260923'),root=path.resolve('output/learning-input-scope-20260924'),hash=b=>createHash('sha256').update(b).digest('hex'),save=(f,v)=>fs.writeFileSync(root+'/'+f,JSON.stringify(v,null,2),{flag:'wx'});
assert(!fs.existsSync(root+'/baseline.json'),'Do not replace a baseline');for(const d of['before','data/users','data/users-by-email','review-only','screenshots','empty-env'])fs.mkdirSync(root+'/'+d,{recursive:true});
const git={};for(const[k,args]of Object.entries({branch:['branch','--show-current'],head:['rev-parse','HEAD'],status:['status','--short'],staged:['diff','--cached','--name-only']})){const r=spawnSync('git',args,{encoding:'utf8',windowsHide:true});assert.equal(r.status,0);git[k]=r.stdout.trim();}
const files=['src/lib/server/learning/model-input.ts','src/lib/server/learning/model-input.test.ts','src/lib/server/learning/quiz-compact.ts','src/lib/server/learning/quiz-compact.test.ts','src/lib/server/learning/quiz-service.ts','src/components/learning/learning-quiz.tsx','src/components/learning/learning-quiz.test.tsx'];
for(const f of files)fs.copyFileSync(f,root+'/before/'+path.basename(f));
const cfg=parseEnv(fs.readFileSync('.env.local','utf8'));assert(cfg.OPENAI_API_KEY);assert.equal(new URL(cfg.OPENAI_BASE_URL).hostname,'tokenhub.vision-intelligence.tech');
const session=JSON.parse(fs.readFileSync(old+'/session.json')),dir='/data/users/'+session.userId;fs.mkdirSync(root+dir,{recursive:true});
const original=old+dir+'/learning-organizer.sqlite',db=new Database(original,{readonly:true});try{assert.equal(db.pragma('integrity_check',{simple:true}),'ok');await db.backup(root+dir+'/learning-organizer.sqlite');}finally{db.close();}
for(const p of['data/users/'+session.userId+'.json','session.json'])fs.copyFileSync(old+'/'+p,root+'/'+p);
for(const f of fs.readdirSync(old+'/data/users-by-email'))if(fs.readFileSync(old+'/data/users-by-email/'+f,'utf8').includes(session.userId))fs.copyFileSync(old+'/data/users-by-email/'+f,root+'/data/users-by-email/'+f);
const snap=new Database(root+dir+'/learning-organizer.sqlite',{readonly:true});try{save('old-rows.json',Object.fromEntries(snap.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'learning_%'").all().map(({name})=>[name,snap.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()])));}finally{snap.close();}
save('data-baseline.json',{source:original,sha256:hash(fs.readFileSync(original)),snapshotMethod:'SQLite online backup'});
save('baseline.json',{at:new Date().toISOString(),git,files:files.map(file=>({file,sha256:hash(fs.readFileSync(file))})),provider:{model:'deepseek-v4-pro',wire:'TokenHub Responses',credentialPresent:true,reasoning:'none',maxRequests:12,maxInputChars:48000,maxOutputTokens:16000,timeoutMs:240000},ocr:0,asr:0,server:0});
save('ds-permits.json',[]);console.log(JSON.stringify({prepared:true,root,requests:0,files:files.length}));
