import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {LearningRepository} from '../../src/lib/server/learning/repository.ts';import {generateLearningQuiz} from '../../src/lib/server/learning/quiz-service.ts';import {organizeLearningText} from '../../src/lib/server/learning/framework-service.ts';import {learningGenerationConfig,generateStudyJson} from '../../src/lib/server/learning/framework-generator.ts';
const root=process.env.LEARNING_CLOSURE_ROOT,label=process.argv[2],save=(f,v)=>fs.writeFileSync(root+'/'+f,JSON.stringify(v,null,2)),plan=JSON.parse(fs.readFileSync(root+'/plan.json')),session=JSON.parse(fs.readFileSync(root+'/session.json')),step=plan.runs.find(r=>r.label===label);assert(step);
const learning=new LearningRepository(path.join(root,'data/users',session.userId),session.userId),started=Date.now();
try{const receipt=JSON.parse(fs.readFileSync(root+'/selection-'+step.pageId+'.json'));assert.deepEqual(receipt.materialIds.slice().sort(),step.materialIds);assert.deepEqual(learning.get(step.pageId).materials.filter(m=>m.selected).map(m=>m.id).sort(),step.materialIds);
 const configured=learningGenerationConfig();let value,row;
 if(step.kind==='framework'){value=await organizeLearningText(learning,step.pageId,{id:step.id,materialIds:step.materialIds});row=learning.database.prepare('SELECT * FROM learning_framework_runs WHERE id=?').get(step.id);}
 else{value=await generateLearningQuiz(learning,step.pageId,{id:step.id,settings:step.settings},{configure:()=>configured,inputView:step.view,generate:async(config,task,prompt,input,schema,signal,diagnostics)=>generateStudyJson(config,task,prompt,{...input,taskContext:{...input.taskContext,learningGoal:step.goal}},schema,signal,diagnostics)});row=learning.database.prepare('SELECT * FROM learning_quiz_runs WHERE id=?').get(step.id);}
 save(label+'-api.json',{entry:'Actual application service used by existing learning API; fixed experimental learningGoal for Quiz only, no answer standards',value,durationMs:Date.now()-started});save(label+'-stored.json',row);
 console.log(JSON.stringify({label,status:row.status,count:row.result_json?JSON.parse(row.result_json).questions?.length:undefined,failure:row.failure,durationMs:Date.now()-started}));
}finally{learning.close();}
