import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import Database from 'better-sqlite3';import {chromium,expect as ex} from '@playwright/test';
import {root,base,save,vault} from './runtime.mjs';
const phase=process.argv[2],secure=vault('read'),session=JSON.parse(fs.readFileSync(root+'/session.json','utf8')),expect=ex.configure({timeout:90000}),plan=JSON.parse(fs.readFileSync(root+'/plan.json','utf8'));
const calls=()=>fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length;
const dbRead=f=>{const d=new Database(root+'/data/users/'+session.userId+'/learning-organizer.sqlite',{readonly:true});try{return f(d);}finally{d.close();}};
const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1080},serviceWorkers:'block'}),tab=await ctx.newPage();ctx.setDefaultTimeout(90000);const errors=[];let stage='login';
await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());tab.on('pageerror',e=>errors.push(e.message));tab.on('dialog',d=>d.accept());
const api=async(suffix='',method='GET',data)=>tab.evaluate(async({url,method,data})=>{const r=await fetch(url,{method,credentials:'same-origin',...(data?{headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});return{status:r.status,value:await r.json()};},{url:base+'/api/learning/pages/'+session.pageId+suffix,method,data});
const area=n=>tab.getByRole('navigation',{name:'学习任务'}).getByRole('button',{name:n,exact:true}).click(),snap=n=>tab.screenshot({path:root+'/screenshots/'+n+'.png',fullPage:true});
const permit=steps=>{assert(!fs.existsSync(root+'/'+phase+'-api.json'),'A finished attempt must not be retried under the same step name');save('ds-permits.json',steps);};
try{
 assert.equal((await ctx.request.post(base+'/api/auth/login',{data:{email:secure.email,password:secure.password}})).status(),200);await tab.goto(base+'/learning/'+session.pageId);
 if(phase.startsWith('overview')){
  stage='overview';await area('阅读框架');await tab.locator('summary').filter({hasText:'章节关系与总览'}).click();const before=(await api('/overview')).value.overview;save(phase+'-before.json',before);
  permit([{name:phase,promptMarker:'任务：在不同批次'}]);const response=tab.waitForResponse(r=>r.url().endsWith('/overview')&&r.request().method()==='POST',{timeout:240000});await tab.getByRole('button',{name:'更新关系总览',exact:true}).click();await snap(phase+'-pending');const r=await response,v=await r.json();save(phase+'-api.json',{status:r.status(),value:v});assert.equal(r.status(),200);const after=(await api('/overview')).value.overview;save(phase+'-saved.json',after);assert.equal(after.latest.status,'completed');assert.equal(after.published.id,after.latest.id);await expect(tab.getByRole('region',{name:'章节关系',exact:true})).toContainText(after.published.result.summary);await snap(phase+'-published');
  const sources=[];for(let i=0;i<after.published.result.items.length;i++)for(let j=0;j<after.published.result.items[i].sources.length;j++){const r=await api('/study-source?'+new URLSearchParams({kind:'overview',id:after.published.id,item:String(i),index:String(j)}));assert.equal(r.status,200);sources.push({item:i,index:j,source:r.value.source});}
  // Source route uses the same public client query shape as the UI; click actual buttons below.
  const relation=tab.getByRole('region',{name:'章节关系',exact:true}).getByRole('article').first();await relation.getByRole('button').first().click();await expect(tab.getByRole('region',{name:'材料原文',exact:true})).toBeVisible();await snap(phase+'-source');await tab.getByRole('button',{name:'关闭原文',exact:true}).click();save(phase+'-sources.json',sources);
 }else if(phase.startsWith('quiz-')){
  stage='quiz';await area('材料');for(const c of await tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox').all())await c.check();const b=tab.getByRole('button',{name:'保存本次范围',exact:true});if(await b.isEnabled())await b.click();
  await area('Quiz 练习');const q=tab.getByRole('region',{name:'单选 Quiz',exact:true});if(!await q.getByLabel('题量',{exact:true}).isVisible()){await q.getByRole('button',{name:'题组与历史',exact:true}).click();await q.getByRole('button',{name:'生成另一组',exact:true}).click();}
  await q.getByLabel('题量',{exact:true}).fill('4');await q.getByLabel('难度').selectOption('challenging');const notes=phase.includes('test');await q.getByRole('checkbox',{name:'纳入所选范围的个人笔记',exact:true}).setChecked(notes);await q.getByRole('checkbox',{name:'纳入所选知识点已保存的补充解释',exact:true}).uncheck();
  permit([{name:phase,promptMarker:'你是学习单选题编写助手'}]);const response=tab.waitForResponse(r=>r.url().endsWith('/quiz')&&r.request().method()==='POST',{timeout:240000});await q.getByRole('button',{name:'生成 Quiz',exact:true}).click();await snap(phase+'-pending');const r=await response,v=await r.json();save(phase+'-api.json',{status:r.status(),value:v});assert.equal(r.status(),200);const quiz=v.quizzes[0];save(phase+'-stored.json',dbRead(d=>d.prepare('SELECT * FROM learning_quiz_runs WHERE id=?').get(quiz.id)));assert.equal(quiz.status,'completed',quiz.failure??quiz.reason);assert(quiz.count>=2);await snap(phase+'-ready');
 }else if(phase.startsWith('qa-')){
  stage='qa';const chosen=JSON.parse(fs.readFileSync('output/learning-synthetic-course-20260923/chosen-node.json','utf8')),f=(await api('/framework')).value.framework,c=f.chapters.find(c=>c.id===chosen.chapterId),n=c.nodes.find(n=>n.id===chosen.nodeId);await area('阅读框架');await tab.getByRole('navigation',{name:'章节目录'}).getByRole('button').nth(f.chapters.indexOf(c)).click();await tab.getByRole('article',{name:n.title,exact:true}).getByRole('button',{name:'没看懂 / 继续追问',exact:true}).click();const dialog=tab.getByRole('dialog',{name:'没看懂 / 继续追问',exact:true});await dialog.getByRole('button',{name:'基于当前知识点开始新对话',exact:true}).click();
  await dialog.getByLabel('继续追问',{exact:true}).fill(plan.qaQuestion);permit([{name:phase,promptMarker:'任务：围绕taskContext.node'}]);const response=tab.waitForResponse(r=>r.url().endsWith('/node-qa')&&r.request().method()==='POST',{timeout:240000});await dialog.getByRole('button',{name:'发送问题',exact:true}).click();const r=await response,v=await r.json();save(phase+'-api.json',{status:r.status(),value:v});assert.equal(r.status(),200);assert(v.conversations.some(c=>c.turns.some(t=>t.question===plan.qaQuestion&&t.status==='completed')));await expect(dialog.getByLabel('继续追问',{exact:true})).toBeEnabled();await snap(phase+'-saved');
 }else if(phase==='framework-metadata'){
  stage='small-framework';await area('材料');const page=(await api()).value.page;for(const[m,i]of page.materials.map((m,i)=>[m,i]))await tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox').nth(i).setChecked(['追加课件','追加记录'].includes(m.title));const b=tab.getByRole('button',{name:'保存本次范围',exact:true});if(await b.isEnabled())await b.click();await area('阅读框架');const f=tab.getByRole('region',{name:'知识框架',exact:true});await f.getByRole('button',{name:'整理新材料',exact:true}).click();permit([{name:phase,promptMarker:'你是学习整理助手'},{name:'overview-attached-metadata',promptMarker:'任务：在不同批次'}]);const response=tab.waitForResponse(r=>r.url().endsWith('/framework')&&r.request().method()==='POST',{timeout:300000});await f.getByRole('button',{name:'整理所选材料',exact:true}).click();const r=await response,v=await r.json();save(phase+'-api.json',{status:r.status(),value:v});assert.equal(r.status(),200);assert.equal(v.framework.runs.at(-1).status,'completed');save(phase+'-saved.json',(await api('/framework')).value);save(phase+'-overview.json',(await api('/overview')).value);await snap(phase+'-saved');
 }else throw Error('Unknown phase');
 assert.deepEqual(errors,[]);save(phase+'-result.json',{status:'PASS_ENGINEERING',calls:calls(),pageErrors:errors});console.log(JSON.stringify({phase,status:'PASS_ENGINEERING',ds:calls()}));
}catch(e){const message=String(e?.message??e).split('Call log:')[0];save(phase+'-failure-'+Date.now()+'.json',{stage,message,ds:calls()});console.error(phase+': '+message);await snap('failure-'+phase).catch(()=>{});process.exitCode=1;}
finally{await browser.close();save(phase+'-exit-'+Date.now()+'.json',{exitCode:process.exitCode??0,stage,browserClosed:true});}
