// Read-only data/receipt audit. The main synthetic course is never opened for writes.
import fs from 'node:fs';import {createHash} from 'node:crypto';import Database from 'better-sqlite3';import assert from 'node:assert/strict';import {root,save} from './runtime.mjs';
const phase=process.argv[2]??'current',hash=b=>createHash('sha256').update(b).digest('hex'),baseline=JSON.parse(fs.readFileSync(root+'/baseline.json','utf8')),old=JSON.parse(fs.readFileSync(root+'/old-rows.json','utf8')),session=baseline.session;
const original=baseline.source+'/data/users/'+session.userId+'/learning-organizer.sqlite';assert.equal(hash(fs.readFileSync(original)),baseline.originalDatabaseSha256,'Original course bytes changed');
const db=new Database(root+'/data/users/'+session.userId+'/learning-organizer.sqlite',{readonly:true}),tables={},current={};
try{assert.equal(db.pragma('integrity_check',{simple:true}),'ok');for(const [table,rows]of Object.entries(old)){const now=db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),rowHashes=new Set(now.map(r=>hash(JSON.stringify(r))));const missing=rows.filter(r=>!rowHashes.has(hash(JSON.stringify(r)))).length;tables[table]={old:rows.length,now:now.length,missingOrChanged:missing};assert.equal(missing,0,table+' old data changed');}
 for(const table of ['learning_pages',...Object.keys(old)]){const rows=db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all();current[table]={rows:rows.length,sha256:hash(JSON.stringify(rows))};}
 if(phase==='before-restart')save('restart-content-before.json',current);
 if(phase==='after-restart')assert.deepEqual(current,JSON.parse(fs.readFileSync(root+'/restart-content-before.json','utf8')),'Saved old and new course content must survive restart exactly');
 save('data-audit-'+phase+'.json',{status:'PASS',snapshotMethod:'SQLite online backup',originalDatabaseSha256:baseline.originalDatabaseSha256,originalUnchanged:true,tables,current});
}finally{db.close();}
const ids=fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).map(f=>Number(f.match(/\d+/)[0])).sort((a,b)=>a-b),ledger=ids.map(n=>{const request=JSON.parse(fs.readFileSync(root+'/ds-request-'+n+'.json','utf8')),response=JSON.parse(fs.readFileSync(root+'/ds-response-'+n+'.json','utf8'));assert.equal(request.body.model,'deepseek-v4-pro');assert(request.inputChars<=48000&&request.body.max_output_tokens<=8000);return{request:n,step:request.step,at:request.at,model:request.body.model,inputChars:request.inputChars,outputLimit:request.body.max_output_tokens,requestSha256:hash(fs.readFileSync(root+'/ds-request-'+n+'.json')),httpStatus:response.httpStatus,terminal:response.terminal,usage:response.usage??null,durationMs:response.durationMs??null};});
assert(ids.length<=12);assert.equal(hash(fs.readFileSync(root+'/plan.json')),fs.readFileSync(root+'/plan.sha256','utf8').trim());save('ledger.json',{requests:ledger.length,ocr:0,asr:0,remoteStarts:0,usedHistoricalParsedAndAsr:true,usageComplete:ledger.every(r=>r.usage!==null),totals:ledger.every(r=>r.usage!==null)?{input:ledger.reduce((s,r)=>s+r.usage.input_tokens,0),output:ledger.reduce((s,r)=>s+r.usage.output_tokens,0),total:ledger.reduce((s,r)=>s+r.usage.total_tokens,0)}:null,ledger});
console.log(JSON.stringify({phase,status:'PASS',originalUnchanged:true,oldRowsPreserved:Object.values(tables).reduce((n,t)=>n+t.old,0),ds:ledger.length,ocr:0,asr:0}));
