import fs from 'node:fs';import net from 'node:net';import {parseEnv} from 'node:util';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';import {root,save,vault} from './runtime.mjs';
let code=0;try{
 const listening=await new Promise(resolve=>{const s=net.connect({host:'127.0.0.1',port:37920});let ended=false;const done=v=>{if(ended)return;ended=true;s.destroy();resolve(v);};s.once('connect',()=>done(true));s.once('error',()=>done(false));s.setTimeout(1500,()=>done(false));});assert.equal(listening,false,'Own application listener must be closed');
 const exits=fs.readdirSync(root).filter(f=>/^runtime-exit-\d+\.json$/.test(f)).sort(),last=JSON.parse(fs.readFileSync(root+'/'+exits.at(-1),'utf8'));assert.equal(last.exitCode,0);assert.equal(last.stopCode,0);
 const secure=vault('read'),env=parseEnv(fs.readFileSync('.env.local','utf8')),secrets=[secure.secret,secure.password,secure.invite,env.OPENAI_API_KEY].filter(Boolean),findings=[];
 for(const f of fs.readdirSync(root)){if(!/\.(jsonl?|log)$/.test(f)||!fs.statSync(root+'/'+f).isFile())continue;const t=fs.readFileSync(root+'/'+f,'utf8');if(secrets.some(s=>t.includes(s)))findings.push(f);}
 save('secret-scan.json',{filesWithSecrets:findings});assert.equal(findings.length,0,'Evidence contains a credential; report only the file name');
 const files=['src/lib/domain/learning-study.ts','src/lib/domain/learning-quiz.ts','src/lib/server/learning/model-input.ts','src/lib/server/learning/model-input.test.ts','src/lib/server/learning/framework-generator.ts','src/lib/server/learning/framework-generator.test.ts','src/lib/server/learning/framework-repository.ts','src/lib/server/learning/study-service.ts','src/lib/server/learning/study-repository.ts','src/lib/server/learning/study.test.ts','src/lib/server/learning/quiz-service.ts','src/lib/server/learning/quiz-repository.ts','src/lib/server/learning/quiz-grounding.ts','src/lib/server/learning/quiz-reference.test.ts','src/lib/client/learning-api.ts','src/components/learning/learning-study.tsx','src/components/learning/learning-study.test.tsx','docs/learning-multisource-closure-trial.md',...fs.readdirSync('scripts/learning-multisource-closure').map(f=>'scripts/learning-multisource-closure/'+f)];
 const hashes=files.map(file=>({file,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')}));save('final-code.json',{at:new Date().toISOString(),files:hashes});
 for(const[name,args]of[['head',['rev-parse','HEAD']],['branch',['branch','--show-current']],['status',['status','--short']],['staged',['diff','--cached','--name-only']],['diff-check',['-c','core.safecrlf=false','diff','--check']]]){const r=spawnSync('git',args,{encoding:'utf8',windowsHide:true});fs.writeFileSync(root+'/final-'+name+'.txt',r.stdout??'');save('final-'+name+'-exit.json',{exitCode:r.status});assert.equal(r.status,0,'git '+name);}
 const syntax=[];for(const f of files.filter(f=>/\.(mjs|cjs)$/.test(f))){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});syntax.push({file:f,exitCode:r.status});assert.equal(r.status,0,f);}save('script-syntax.json',syntax);
 const ledger=JSON.parse(fs.readFileSync(root+'/ledger.json','utf8'));assert.equal(ledger.requests,9);assert.equal(ledger.ocr,0);assert.equal(ledger.asr,0);assert.deepEqual(JSON.parse(fs.readFileSync(root+'/ds-permits.json','utf8')),[]);
 save('final-cleanup.json',{status:'PASS',at:new Date().toISOString(),localPort:37920,listening:false,runtime:last,ds:ledger.requests,ocr:0,asr:0,remoteAccesses:0,sshOrTunnelStarted:false,secureConfigRetained:true,courseDataRetained:true});console.log(JSON.stringify({status:'PASS',ds:9,ocr:0,asr:0,listenerClosed:true,secretFindings:0,sourceFiles:files.length}));
}catch(e){console.error(e.message);code=1;}finally{save('finalize-exit.json',{exitCode:code,at:new Date().toISOString()});process.exitCode=code;}
