// Reopen new real results and resolve every new overview/answer citation via authenticated API.
import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium,expect as ex} from '@playwright/test';import {root,base,save as write,vault} from './runtime.mjs';
const prefix=process.argv.includes('--postrestart')?'restart-':'',save=(name,value)=>write(prefix+name,value);
const secure=vault('read'),session=JSON.parse(fs.readFileSync(root+'/session.json','utf8')),plan=JSON.parse(fs.readFileSync(root+'/plan.json','utf8')),expect=ex.configure({timeout:90000}),ds=()=>fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length,before=ds();
const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1080},serviceWorkers:'block'}),tab=await ctx.newPage();ctx.setDefaultTimeout(90000);await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
const api=async suffix=>tab.evaluate(async url=>{const r=await fetch(url,{credentials:'same-origin'});return{status:r.status,value:await r.json()};},'/api/learning/pages/'+session.pageId+suffix),snap=n=>tab.screenshot({path:root+'/screenshots/'+prefix+n+'.png',fullPage:true}),area=n=>tab.getByRole('navigation',{name:'学习任务'}).getByRole('button',{name:n,exact:true}).click();
try{
 assert.equal((await ctx.request.post(base+'/api/auth/login',{data:{email:secure.email,password:secure.password}})).status(),200);await tab.goto(base+'/learning/'+session.pageId);
 await area('材料');for(const c of await tab.getByRole('region',{name:'已保存材料'}).getByRole('checkbox').all())await c.check();const selection=tab.getByRole('button',{name:'保存本次范围',exact:true});if(await selection.isEnabled())await selection.click();await snap('final-materials-reused');
 const framework=(await api('/framework')).value.framework,overview=(await api('/overview')).value.overview;save('final-framework.json',framework);save('final-overview.json',overview);assert.equal(overview.latest.status,'completed');assert(overview.published.result.items.length);
 await area('阅读框架');await tab.locator('summary').filter({hasText:'章节关系与总览'}).click();await tab.getByLabel('未发布关系说明',{exact:true}).locator('summary').click();await snap('final-overview-rejections');
 const sources=[];for(let i=0;i<overview.published.result.items.length;i++)for(let j=0;j<overview.published.result.items[i].sources.length;j++){const r=await api('/study-source?'+new URLSearchParams({kind:'overview',id:overview.published.id,item:String(i),index:String(j)}));assert.equal(r.status,200);sources.push({kind:'overview',item:i,index:j,source:r.value.source});}
 const rel=tab.getByRole('region',{name:'章节关系',exact:true});await rel.getByRole('button',{name:/物理页/}).first().click();await expect(tab.locator('canvas[data-ready=true]')).toBeVisible();await snap('final-overview-pdf-region');await tab.getByRole('button',{name:'关闭原文',exact:true}).click();
 const chosen=JSON.parse(fs.readFileSync('output/learning-synthetic-course-20260923/chosen-node.json','utf8')),c=framework.chapters.find(c=>c.id===chosen.chapterId),n=c.nodes.find(n=>n.id===chosen.nodeId);await tab.getByRole('navigation',{name:'章节目录'}).getByRole('button').nth(framework.chapters.indexOf(c)).click();await tab.getByRole('article',{name:n.title,exact:true}).getByRole('button',{name:'没看懂 / 继续追问',exact:true}).click();const dialog=tab.getByRole('dialog',{name:'没看懂 / 继续追问',exact:true});await expect(dialog).toContainText(plan.qaQuestion);await expect(dialog).toContainText('材料外');await snap('final-qa-reopened');
 const conversations=(await api('/node-qa?'+new URLSearchParams({chapter:c.id,node:n.id}))).value.conversations,turn=conversations.flatMap(c=>c.turns).find(t=>t.question===plan.qaQuestion);assert.equal(turn.status,'completed');for(let j=0;j<turn.answer.items.length;j++){const r=await api('/study-source?'+new URLSearchParams({kind:'answer',id:turn.id,item:'0',index:String(j)}));assert.equal(r.status,200);sources.push({kind:'answer',index:j,source:r.value.source});}
 await dialog.getByRole('article').filter({hasText:plan.qaQuestion}).getByRole('button',{name:/课程讲解.*第/}).first().click();await expect(tab.getByRole('region',{name:'材料原文',exact:true})).toBeVisible();await snap('final-asr-time-source');save('final-source-reads.json',sources);assert.equal(ds(),before);save('inspect-result.json',{status:'PASS',sourceReads:sources.length,dsBefore:before,dsAfter:ds()});console.log(JSON.stringify({status:'PASS',sourceReads:sources.length,ds:ds()}));
}catch(e){save('inspect-failure-'+Date.now()+'.json',{message:String(e.message).split('Call log:')[0]});console.error(String(e.message).split('Call log:')[0]);await snap('inspect-failure').catch(()=>{});process.exitCode=1;}
finally{await browser.close();save('inspect-exit-'+Date.now()+'.json',{exitCode:process.exitCode??0,browserClosed:true});}
