import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import Database from 'better-sqlite3';
const old=path.resolve('output/learning-synthetic-course-20260923'),root=path.resolve('output/learning-multisource-closure-20260923');
assert(!fs.existsSync(root+'/baseline.json'),'Existing closure baseline must not be overwritten');fs.mkdirSync(root,{recursive:true});fs.mkdirSync(root+'/screenshots',{recursive:true});fs.mkdirSync(root+'/review-only',{recursive:true});
const session=JSON.parse(fs.readFileSync(old+'/session.json','utf8')),userDir='/data/users/'+session.userId;fs.mkdirSync(root+userDir,{recursive:true});
const db=new Database(old+userDir+'/learning-organizer.sqlite',{readonly:true});try{assert.equal(db.pragma('integrity_check',{simple:true}),'ok');await db.backup(root+userDir+'/learning-organizer.sqlite');}finally{db.close();}
fs.copyFileSync(old+'/data/users/'+session.userId+'.json',root+'/data/users/'+session.userId+'.json');fs.mkdirSync(root+'/data/users-by-email',{recursive:true});
for(const f of fs.readdirSync(old+'/data/users-by-email'))if(fs.readFileSync(old+'/data/users-by-email/'+f,'utf8').includes(session.userId))fs.copyFileSync(old+'/data/users-by-email/'+f,root+'/data/users-by-email/'+f);
fs.copyFileSync(old+'/session.json',root+'/session.json');
const hashFile=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const tables=['learning_materials','learning_parsed_documents','learning_audio_runs','learning_audio_chunks','learning_audio_transcripts','learning_framework_runs','learning_framework_chapters','learning_overview_runs','learning_node_conversations','learning_node_turns','learning_answer_notes','learning_quiz_runs','learning_quiz_attempts'];
const snap=new Database(root+userDir+'/learning-organizer.sqlite',{readonly:true}),records={};try{for(const t of tables){const rows=snap.prepare('SELECT * FROM '+t+' ORDER BY rowid').all();records[t]={count:rows.length,hash:createHash('sha256').update(JSON.stringify(rows)).digest('hex')};}fs.writeFileSync(root+'/old-rows.json',JSON.stringify(Object.fromEntries(tables.map(t=>[t,snap.prepare('SELECT * FROM '+t+' ORDER BY rowid').all()]))));}finally{snap.close();}
const files=['src/lib/domain/learning-study.ts','src/lib/server/learning/study-service.ts','src/lib/server/learning/study-repository.ts','src/lib/server/learning/framework-generator.ts','src/lib/server/learning/framework-repository.ts','src/lib/server/learning/quiz-service.ts','src/lib/server/learning/quiz-grounding.ts','src/lib/server/learning/quiz-repository.ts','src/components/learning/learning-study.tsx'];
for(const f of files){const target=root+'/before/'+f;fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(f,target);}
const git={};for(const[k,args]of Object.entries({branch:['branch','--show-current'],head:['rev-parse','HEAD'],status:['status','--short'],staged:['diff','--cached','--name-only'],diff:['diff','--stat']})){const r=spawnSync('git',args,{encoding:'utf8',windowsHide:true});assert.equal(r.status,0);git[k]=r.stdout.trim();}
fs.writeFileSync(root+'/baseline.json',JSON.stringify({at:new Date().toISOString(),git,source:old,snapshotMethod:'SQLite online backup; original account data not written',originalDatabaseSha256:hashFile(old+userDir+'/learning-organizer.sqlite'),frozenSha256:hashFile(old+'/frozen.json'),session,records,files:files.map(f=>({file:f,sha256:hashFile(f)}))},null,2));
fs.writeFileSync(root+'/plan.json',JSON.stringify({batch:'multisource-closure-20260923',provider:'TokenHub Responses',model:'deepseek-v4-pro',maxRequests:12,maxInputChars:48000,maxOutputTokens:8000,maxRefinementRounds:3,ocr:0,asr:0,reusedSource:old,primary:['overview existing 11 chapters','joint Quiz all five saved materials, no extras, 4 questions, practice','node QA: uncertain ASR names/numbers and rule boundaries, one labelled example','joint Quiz all five saved materials with explicit personal notes, 4 questions, test','small framework regeneration of saved second-batch PDF/TXT only to verify metadata boundary','attached overview after that framework'],remaining:'Only named manual rechecks for documented issues, within 12; no automatic retry',checkpoints:['valid cross-batch Window relations with actual paragraph support','control metadata never course facts','stem quantities and all reasons share premises','coexisting obstacles do not become exclusive','no unstated ordering','ASR names/numbers stay uncertain, no script correction','rule explanation does not authorize changing capacity','letter independence in every question field','old rows unchanged and no repeated OCR/ASR'],reviewOnlyExcluded:['authoring script','TTS script','answer standards','manual review checklists']},null,2));
fs.writeFileSync(root+'/ds-permits.json','[]');console.log(JSON.stringify({snapshot:'PASS',root,records:Object.fromEntries(Object.entries(records).map(([t,v])=>[t,v.count])),providersCalled:0}));
