import fs from 'node:fs';import path from 'node:path';import net from 'node:net';import {parseEnv} from 'node:util';import {spawn,spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
import {vault} from '../learning-synthetic-course/trial.mjs';
export {vault};export const root=path.resolve('output/learning-multisource-closure-20260923'),base='http://127.0.0.1:37920',save=(f,v)=>fs.writeFileSync(root+'/'+f,JSON.stringify(v,null,2));
export function environment(live=false,dist='next'){
 const cfg={...parseEnv(fs.readFileSync('.env.local','utf8')),...process.env},secure=vault('read'),env={};assert(cfg.OPENAI_API_KEY&&new URL(cfg.OPENAI_BASE_URL).hostname==='tokenhub.vision-intelligence.tech');
 for(const[k,v]of Object.entries(process.env))if(/^(path|pathext|systemroot|windir|comspec|temp|tmp|userprofile|localappdata|appdata|homedrive|homepath|processor_architecture|number_of_processors)$/i.test(k))env[k]=v;
 for(const k of['OPENAI_API_KEY','OPENAI_BASE_URL','OPENAI_AUTH_HEADER_MODE'])if(live&&cfg[k])env[k]=cfg[k];
 return {...env,APP_DATA_DIR:root+'/data',DATA_DIR:root+'/data',APP_STORAGE_MODE:'local',DAILY_BRIEF_INVITE_CODES:secure.invite,DAILY_BRIEF_E2E_DIST_DIR:path.relative(process.cwd(),root+'/'+dist).replaceAll('\\','/'),DAILY_BRIEF_E2E_TSCONFIG:path.relative(process.cwd(),root+'/tsconfig.json').replaceAll('\\','/'),LEARNING_AI_PROVIDER:live?'tokenhub':'',LEARNING_AI_MODEL:'deepseek-v4-pro',LEARNING_AI_MAX_INPUT_CHARS:'48000',LEARNING_AI_MAX_OUTPUT_TOKENS:'8000',LEARNING_ASR_AUDIO_CAPABILITY_SECRET:secure.secret,LEARNING_CLOSURE_ROOT:root,LEARNING_VALIDATION_REPO:process.cwd(),LEARNING_CLOSURE_LIVE:live?'1':'0',NEXT_TELEMETRY_DISABLED:'1',NODE_OPTIONS:`--max-old-space-size=8192 --require="${path.resolve('scripts/learning-multisource-closure/guard.cjs').replaceAll('\\','/')}"`};
}
if(path.resolve(process.argv[1]??'')===fileURLToPath(import.meta.url)){
 const mode=process.argv[2];if(mode==='stop'){fs.writeFileSync(root+'/stop','stop');console.log('Closure stop requested');}
 else if(mode==='status'){let online=false;try{online=(await fetch(base+'/api/auth/session',{signal:AbortSignal.timeout(1000)})).status<500;}catch{}console.log(JSON.stringify({base,online,ds:fs.readdirSync(root).filter(f=>/^ds-request-\d+\.json$/.test(f)).length}));}
 else if(mode==='start'){
  await new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(37920,'127.0.0.1',()=>s.close(resolve));});
  const live=process.argv.includes('--live'),prod=process.argv.includes('--production'),env=environment(live,prod?'build':'next'),run=Date.now(),before=fs.readFileSync('next-env.d.ts');
  if(fs.existsSync(root+'/stop'))fs.unlinkSync(root+'/stop');fs.writeFileSync(root+'/tsconfig.json',JSON.stringify({extends:path.resolve('tsconfig.json').replaceAll('\\','/'),compilerOptions:{incremental:false,baseUrl:process.cwd().split(path.sep).join('/'),paths:{'@/*':['./src/*']}},include:[path.resolve('src/**/*.ts').replaceAll('\\','/'),path.resolve('src/**/*.tsx').replaceAll('\\','/')],exclude:[path.resolve('node_modules').replaceAll('\\','/')]}));
  const log=root+'/runtime-'+run+'.log',child=spawn(process.execPath,['node_modules/next/dist/bin/next',prod?'start':'dev','--hostname','127.0.0.1','-p','37920'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});
  const secrets=[env.OPENAI_API_KEY,env.LEARNING_ASR_AUDIO_CAPABILITY_SECRET,env.DAILY_BRIEF_INVITE_CODES].filter(Boolean);for(const s of[child.stdout,child.stderr])s.on('data',b=>{let t=String(b);for(const v of secrets)t=t.replaceAll(v,'[REDACTED]');fs.appendFileSync(log,t);});
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));let exitCode=0;process.on('SIGINT',()=>fs.writeFileSync(root+'/stop','stop'));process.on('SIGTERM',()=>fs.writeFileSync(root+'/stop','stop'));
  try{const until=Date.now()+180000;let ready=false;while(Date.now()<until){assert(child.exitCode===null,'Next exited');try{ready=(await fetch(base+'/api/auth/session',{signal:AbortSignal.timeout(1200)})).status<500;}catch{}if(ready)break;await sleep(300);}assert(ready,'Next not ready');save('runtime.json',{base,pid:process.pid,child:child.pid,live,production:prod,at:new Date().toISOString()});console.log('Closure runtime READY '+base+(live?' (bounded DS only)':' (saved-data mode)'));while(!fs.existsSync(root+'/stop')&&Date.now()-run<3*3600000){assert(child.exitCode===null);await sleep(400);}}
  catch(e){exitCode=1;save('runtime-failure-'+run+'.json',{message:e.message});console.log('Closure runtime failed: '+e.message);}
  finally{let stopCode=0;if(child.exitCode===null)stopCode=spawnSync('taskkill',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'}).status;if(fs.readFileSync('next-env.d.ts','utf8').includes('learning-multisource-closure'))fs.writeFileSync('next-env.d.ts',before);save('runtime-exit-'+run+'.json',{exitCode,stopCode,child:child.pid,at:new Date().toISOString()});process.exitCode=exitCode;}
 }else throw Error('start/status/stop');
}
